id: Pentera Run Scan
version: -1
name: Pentera Run Scan
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 8bd17e81-ec65-4650-80e6-4dc323a81362
    type: start
    task:
      id: 8bd17e81-ec65-4650-80e6-4dc323a81362
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '3'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: 1c694c10-459d-4fb3-85ba-1695dfe88bb2
    type: regular
    task:
      id: 1c694c10-459d-4fb3-85ba-1695dfe88bb2
      version: -1
      name: Run Pentera Template
      description: ''
      script: '|||pentera-run-template-by-name'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      templateName:
        simple: ${inputs.Pentera Task Name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: 38441ed3-fe8c-43aa-841d-5f0f4836e567
    type: playbook
    task:
      id: 38441ed3-fe8c-43aa-841d-5f0f4836e567
      version: -1
      name: GenericPolling
      description: ''
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${Pentera.TaskRun.ID}
      Interval:
        simple: '1'
      PollingCommandArgName:
        simple: taskRunId
      PollingCommandName:
        simple: pentera-get-task-run-status
      Timeout:
        simple: '60'
      dt:
        simple: Pentera.TaskRun(val.Status === 'Running' || val.Status === 'Cleaning
          up').ID
    separatecontext: false
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '3':
    id: '3'
    taskid: f55d4d63-0622-497f-839a-0559c9c0138f
    type: title
    task:
      id: f55d4d63-0622-497f-839a-0559c9c0138f
      version: -1
      name: Start the Scan
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: e2da392a-2be6-49af-8b09-fcb00ed780c8
    type: title
    task:
      id: e2da392a-2be6-49af-8b09-fcb00ed780c8
      version: -1
      name: Wait For The Scan To Complete
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '5':
    id: '5'
    taskid: 83939dcd-f56f-4eb5-8a69-4e615c3a69cd
    type: title
    task:
      id: 83939dcd-f56f-4eb5-8a69-4e615c3a69cd
      version: -1
      name: Collect The Full Action Report
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '6'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 835
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: d5c4ff25-8fba-4a7a-8dc7-466064e9e0a2
    type: regular
    task:
      id: d5c4ff25-8fba-4a7a-8dc7-466064e9e0a2
      version: -1
      name: Retrieve The Full Action Report
      description: ''
      script: '|||pentera-get-task-run-full-action-report'
      type: regular
      iscommand: true
      brand: ''
    scriptarguments:
      taskRunId:
        simple: ${Pentera.TaskRun.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1025,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Pentera Task Name
  value: {}
  required: true
  description: The name of the Pentera task to run
outputs: []
description: ''
fromversion: 5.0.0
