id: generic-sql
version: -1
name: generic-sql
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: aaa9aa15-4aaf-4f34-8157-4e32b13c3bf1
    type: start
    task:
      id: aaa9aa15-4aaf-4f34-8157-4e32b13c3bf1
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 7de877cc-098d-4459-8567-8036266cd4ca
    type: regular
    task:
      id: 7de877cc-098d-4459-8567-8036266cd4ca
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit:
        simple: "10"
      query:
        simple: select * from TestTable
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 0935ee64-bf98-42c3-86be-b5c93714f79b
    type: condition
    task:
      id: 0935ee64-bf98-42c3-86be-b5c93714f79b
      version: -1
      name: Check query
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              simple: ${GenericSQL.GenericSQL.Result}
            iscontext: true
          right:
            value:
              simple: "4"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: efca38bd-4d0b-421c-8ff2-1324865bd4a0
    type: regular
    task:
      id: efca38bd-4d0b-421c-8ff2-1324865bd4a0
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit: {}
      query:
        simple: Insert into TestTable(ID, LastName, FirstName) values (11511, 'playbook',
          'test')
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: e8f8ac1b-aed2-42aa-87cf-3f2c19ad6c26
    type: condition
    task:
      id: e8f8ac1b-aed2-42aa-87cf-3f2c19ad6c26
      version: -1
      name: Check insert
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "18"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              simple: ${GenericSQL.GenericSQL.Result}
            iscontext: true
          right:
            value:
              simple: "5"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: a9543f15-8f5e-4bcf-8fdc-8f55dfede4a3
    type: regular
    task:
      id: a9543f15-8f5e-4bcf-8fdc-8f55dfede4a3
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit:
        simple: "10"
      query:
        simple: select * from TestTable
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 785
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 019d0763-addf-402c-86f8-2ad28b9690c8
    type: regular
    task:
      id: 019d0763-addf-402c-86f8-2ad28b9690c8
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit: {}
      query:
        simple: Delete FROM TestTable WHERE ID=11511
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: b04e6fcd-7411-4031-8ae9-e53aa75bda0a
    type: regular
    task:
      id: b04e6fcd-7411-4031-8ae9-e53aa75bda0a
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit:
        simple: "10"
      query:
        simple: select * from TestTable
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1485
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: fe5b512e-3d66-4eda-806e-accb2f1103a8
    type: condition
    task:
      id: fe5b512e-3d66-4eda-806e-accb2f1103a8
      version: -1
      name: Check Delete
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "20"
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              simple: ${GenericSQL.GenericSQL.Result}
            iscontext: true
          right:
            value:
              simple: "4"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1640
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: eb20fc66-8552-4336-8f4b-c6e56e76213d
    type: title
    task:
      id: eb20fc66-8552-4336-8f4b-c6e56e76213d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1855
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 37cf165a-bf96-4383-8f28-e833925eedb1
    type: regular
    task:
      id: 37cf165a-bf96-4383-8f28-e833925eedb1
      version: -1
      name: PrintErrorEntry
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Query failed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -30,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: 497fefd8-cfdb-4696-83d6-4a3aa3a34a80
    type: regular
    task:
      id: 497fefd8-cfdb-4696-83d6-4a3aa3a34a80
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: 800097df-1502-4c3e-8e25-fa9598e1c3a4
    type: regular
    task:
      id: 800097df-1502-4c3e-8e25-fa9598e1c3a4
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 635
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: 82c49b09-45b9-41c7-8054-270fbc26eae2
    type: regular
    task:
      id: 82c49b09-45b9-41c7-8054-270fbc26eae2
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 20ee811e-1025-4da4-8de7-9b8440e0a07e
    type: regular
    task:
      id: 20ee811e-1025-4da4-8de7-9b8440e0a07e
      version: -1
      name: query
      script: Generic SQL|||query
      type: regular
      iscommand: true
      brand: Generic SQL
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      bind_variables_names: {}
      bind_variables_values: {}
      limit: {}
      query:
        simple: Delete FROM TestTable WHERE ID=11511
      skip: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: a56f2e7f-560a-4e68-84b1-e1f38acfc572
    type: regular
    task:
      id: a56f2e7f-560a-4e68-84b1-e1f38acfc572
      version: -1
      name: PrintErrorEntry
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Insert failed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -20,
          "y": 1320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 046d5ce3-25f2-4acd-8004-98381967a174
    type: regular
    task:
      id: 046d5ce3-25f2-4acd-8004-98381967a174
      version: -1
      name: PrintErrorEntry
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Delete failed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": 1840
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2245,
        "width": 860,
        "x": -30,
        "y": -310
      }
    }
  }
inputs: []
outputs: []
