id: Fidelis-Test
version: -1
name: Fidelis-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e0426a07-bf37-4db5-879c-50caf94ea561
    type: start
    task:
      id: e0426a07-bf37-4db5-879c-50caf94ea561
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: a35443ca-e509-48c1-80f0-c38f421523ff
    type: regular
    task:
      id: a35443ca-e509-48c1-80f0-c38f421523ff
      version: -1
      name: Start Clean
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "11"
      - "14"
      - "17"
      - "19"
      - "21"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 01e91474-b487-4ccd-881d-f1b278a0111d
    type: regular
    task:
      id: 01e91474-b487-4ccd-881d-f1b278a0111d
      version: -1
      name: Get Alarms
      script: '|||fidelis-list-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      end_time: {}
      ioc: {}
      severity: {}
      start_time: {}
      threat_score: {}
      time_frame:
        simple: Last 30 Days
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 4fa6b17f-54ca-4d9a-84ac-e7fa9102e3de
    type: regular
    task:
      id: 4fa6b17f-54ca-4d9a-84ac-e7fa9102e3de
      version: -1
      name: Get Alarms - custom time frame
      script: '|||fidelis-list-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      end_time:
        simple: 2019-01-11T09:50:48Z
      ioc: {}
      severity: {}
      start_time:
        simple: 2019-01-09T07:50:48Z
      threat_score: {}
      time_frame: {}
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 1d62d0b8-ab8e-40c2-87a2-d0149c2c79f4
    type: condition
    task:
      id: 1d62d0b8-ab8e-40c2-87a2-d0149c2c79f4
      version: -1
      name: Check Get Alerts
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Fidelis.Alert.ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 319ba3c0-308e-4d59-8046-83754d75b559
    type: regular
    task:
      id: 319ba3c0-308e-4d59-8046-83754d75b559
      version: -1
      name: Error
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Test condition was not satisfied.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: d8a0671a-54de-4967-8f23-cc11eda876f8
    type: regular
    task:
      id: d8a0671a-54de-4967-8f23-cc11eda876f8
      version: -1
      name: Get Specific Alert
      script: '|||fidelis-get-alert'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      alert_id:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: eaebd696-4811-45be-8df0-253d6ae2add3
    type: condition
    task:
      id: eaebd696-4811-45be-8df0-253d6ae2add3
      version: -1
      name: Check Get Alert
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Fidelis.Alert.Protocol
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 404d618c-60de-46eb-8f56-913a5bc7ee67
    type: title
    task:
      id: 404d618c-60de-46eb-8f56-913a5bc7ee67
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 12c86bdb-ef5e-4927-853b-726e0a4dd481
    type: regular
    task:
      id: 12c86bdb-ef5e-4927-853b-726e0a4dd481
      version: -1
      name: Get Alert report
      script: '|||fidelis-get-alert-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      alert_id:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 1b781c36-3c5d-4bc3-8da7-a4b6e8f4e2f4
    type: regular
    task:
      id: 1b781c36-3c5d-4bc3-8da7-a4b6e8f4e2f4
      version: -1
      name: Get Malware Data
      script: '|||fidelis-get-malware-data'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 500,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: e584fa02-2a13-46de-826b-a51a65dc2bfa
    type: regular
    task:
      id: e584fa02-2a13-46de-826b-a51a65dc2bfa
      version: -1
      name: Get Pcap Components
      script: '|||fidelis-list-pcap-components'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 930,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 0cf7c8fd-7994-4e8d-87e7-8c8177926573
    type: condition
    task:
      id: 0cf7c8fd-7994-4e8d-87e7-8c8177926573
      version: -1
      name: Check Pcap Components
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Fidelis.Component.IP
            iscontext: true
    view: |-
      {
        "position": {
          "x": 930,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 48eac86a-177d-4e66-88e2-dfd33d332a55
    type: regular
    task:
      id: 48eac86a-177d-4e66-88e2-dfd33d332a55
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Failed to get Pcap Component
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 940,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 1bcb60da-c4d8-447a-83bc-755b08b187d7
    type: regular
    task:
      id: 1bcb60da-c4d8-447a-83bc-755b08b187d7
      version: -1
      name: Get Alert by UUID
      description: Get alert by UUID
      script: '|||fidelis-get-alert-by-uuid'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      alert_uuid:
        simple: 2d189aef-a7bd-11e9-8c7d-0e2fc66832d6
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: e9b7857e-7fc4-4f6c-8a45-007e2ae1645e
    type: regular
    task:
      id: e9b7857e-7fc4-4f6c-8a45-007e2ae1645e
      version: -1
      name: List alerts by IP
      description: List alerts by source IP or destination IP
      script: '|||fidelis-list-alerts-by-ip'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      dest_ip: {}
      end_time: {}
      src_ip:
        simple: 10.12.16.101 # disable-secrets-detection
      start_time: {}
      time_frame: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1120,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: e82c7c7a-e410-46b8-8e16-77fb57f92e20
    type: regular
    task:
      id: e82c7c7a-e410-46b8-8e16-77fb57f92e20
      version: -1
      name: List Metadata
      description: Get metadata list
      script: '|||fidelis-list-metadata'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      client_ip: {}
      end_time: {}
      request_direction: {}
      server_ip: {}
      start_time: {}
      time_frame:
        simple: Last 30 Days
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1580,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 688c0a8e-be0c-4001-86a7-3330e7db1b18
    type: title
    task:
      id: 688c0a8e-be0c-4001-86a7-3330e7db1b18
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1380,
          "y": 815
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 0a12516f-4aee-4848-8971-c1df4c488b82
    type: regular
    task:
      id: 0a12516f-4aee-4848-8971-c1df4c488b82
      version: -1
      name: Download Malware
      description: Download a malware file from a specified alert
      script: '|||fidelis-download-malware-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      alert_id:
        simple: "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -400,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 6c36ae84-e7ee-41b4-84d1-121e47511485
    type: condition
    task:
      id: 6c36ae84-e7ee-41b4-84d1-121e47511485
      version: -1
      name: Check file
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "23"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: InfoFile.EntryID
            iscontext: true
    view: |-
      {
        "position": {
          "x": -400,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: e6f19321-eff3-4c33-8a75-1184ae5ec52d
    type: regular
    task:
      id: e6f19321-eff3-4c33-8a75-1184ae5ec52d
      version: -1
      name: Download PCAP File
      description: Download the PCAP file from an alert
      script: '|||fidelis-download-pcap-file'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      alert_id:
        simple: "12"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -830,
          "y": 330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "22":
    id: "22"
    taskid: fda289ef-a4a8-43dd-89e4-3c2ec0ee1657
    type: condition
    task:
      id: fda289ef-a4a8-43dd-89e4-3c2ec0ee1657
      version: -1
      name: Check file
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "23"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: InfoFile.EntryID
            iscontext: true
    view: |-
      {
        "position": {
          "x": -830,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: d9f1429c-5f5c-4f38-833b-c40f5ae713f8
    type: title
    task:
      id: d9f1429c-5f5c-4f38-833b-c40f5ae713f8
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -660,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 2790,
        "x": -830,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
