id: Test-PcapHTTPExtractor
version: -1
name: Test-PcapHTTPExtractor
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b6b01734-7172-4284-81de-278fe988bde7
    type: start
    task:
      id: b6b01734-7172-4284-81de-278fe988bde7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: f96f028e-8123-43d7-8e67-c456a131b9a1
    type: regular
    task:
      id: f96f028e-8123-43d7-8e67-c456a131b9a1
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 841d939a-133d-4dd5-8b31-6faf82158dfb
    type: regular
    task:
      id: 841d939a-133d-4dd5-8b31-6faf82158dfb
      version: -1
      name: Get Remote File
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/TestPcapPost.pcap
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 355
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: 441a994e-439b-4c5f-840d-8e6130aea204
    type: regular
    task:
      id: 441a994e-439b-4c5f-840d-8e6130aea204
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 975
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: b8e6545c-44c9-4187-8bd3-0d132545d2e7
    type: title
    task:
      id: b8e6545c-44c9-4187-8bd3-0d132545d2e7
      version: -1
      name: We got good results
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1180
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: c02d906d-6733-4986-8e07-34437616ca43
    type: regular
    task:
      id: c02d906d-6733-4986-8e07-34437616ca43
      version: -1
      name: PcapHTTPExtractor
      scriptName: PcapHTTPExtractor
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      pcapFileName: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 535
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: d8258c67-177e-43f5-86fa-667452f7ef05
    type: condition
    task:
      id: d8258c67-177e-43f5-86fa-667452f7ef05
      version: -1
      name: IsPcapFlowCorrect
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PcapHTTPExtractor
                accessor: Flows.[3].HttpDate
                transformers:
                - operator: trim
            iscontext: true
          right:
            value:
              simple: 2019-01-14T11:20:42
    view: |-
      {
        "position": {
          "x": 50,
          "y": 700
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "10_7_yes": 0.89
    },
    "paper": {
      "dimensions": {
        "height": 1195,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
