id: Panorama Query Logs For Indicators Test
version: -1
name: Panorama Query Logs For Indicators Test
description: This is a test playbook for Panorama Query Logs For Indicators
fromversion: 4.5.0
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bc808813-c98b-48e8-8aa6-aca287120872
    type: start
    task:
      id: bc808813-c98b-48e8-8aa6-aca287120872
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 1fd30e08-2913-4a2e-882d-87c2513a64e1
    type: title
    task:
      id: 1fd30e08-2913-4a2e-882d-87c2513a64e1
      version: -1
      name: Done
      description: Header
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: ea17a0ce-9bbd-4c52-8a8e-9407cd3ff013
    type: regular
    task:
      id: ea17a0ce-9bbd-4c52-8a8e-9407cd3ff013
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 8261ea22-c615-4c52-8eee-07de32e02ca6
    type: playbook
    task:
      id: 8261ea22-c615-4c52-8eee-07de32e02ca6
      version: -1
      name: Panorama Query Logs For Indicators1
      description: 'Query Panorama Logs of types in one playbook: traffic, threat,
        url, data-filtering and wildfire. The playbook accepts inputs such as IP.
        hash, url.'
      playbookName: Panorama Query Logs For Indicators
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      filedigest:
        simple: 4f79697b40d0932e91105bd496908f8e02c130a0e36f6d3434d6243e79ef82e0,78745bbe69460b92369c1536408ff52a07465cd1300b648b27a991011cf576db
      ip:
        simple: 8.8.8.8,192.168.1.12
      log_type:
        simple: traffic,threat,wildfire,data,url
      url:
        simple: microsoft.com,windowsupdate.com
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 615,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
