id: CanaryTools Test
version: -1
name: CanaryTools Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e678be76-11aa-4525-801e-96ffba38bb32
    type: start
    task:
      id: e678be76-11aa-4525-801e-96ffba38bb32
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 54b0a54d-34f6-4d0f-8af5-f88fa8e9f97c
    type: regular
    task:
      id: 54b0a54d-34f6-4d0f-8af5-f88fa8e9f97c
      version: -1
      name: canarytools-check-whitelist
      description: Check whether a given IP and port are whitelisted
      script: Thinkst Canary|||canarytools-check-whitelist
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      ip:
        simple: 8.8.8.8
      port:
        simple: "45"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 9180a147-e0e6-44e8-8a59-8563bb735d73
    type: regular
    task:
      id: 9180a147-e0e6-44e8-8a59-8563bb735d73
      version: -1
      name: canarytools-edit-alert-status
      description: Edit the status for an Alert in Canary Tools
      script: Thinkst Canary|||canarytools-edit-alert-status
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      alertID:
        simple: incident:canarytoken:d6fe0ae4dfd36cc3cc6d9d4f::1548593719 # disable-secrets-detection
      status:
        simple: Acknowledge
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: e370f4c0-d5b2-41d1-8261-e8ce4d114812
    type: regular
    task:
      id: e370f4c0-d5b2-41d1-8261-e8ce4d114812
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: 7039a295-df9e-4b53-851b-afb684e7bc41
    type: regular
    task:
      id: 7039a295-df9e-4b53-851b-afb684e7bc41
      version: -1
      name: canarytools-list-canaries
      description: List all registered Canaries
      script: Thinkst Canary|||canarytools-list-canaries
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "14"
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: fc385c73-8493-4b29-812c-e50937093bd7
    type: regular
    task:
      id: fc385c73-8493-4b29-812c-e50937093bd7
      version: -1
      name: canarytools-list-tokens
      description: List all Canary tokens
      script: Thinkst Canary|||canarytools-list-tokens
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: faa4b2c2-2396-42ce-82c1-05d03de7b649
    type: regular
    task:
      id: faa4b2c2-2396-42ce-82c1-05d03de7b649
      version: -1
      name: canarytools-edit-alert-status
      description: Edit the status for an Alert in Canary Tools
      script: Thinkst Canary|||canarytools-edit-alert-status
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      alertID:
        simple: incident:canarytoken:d6fe0ae4dfd36cc3cc6d9d4f::1548593719 # disable-secrets-detection
      status:
        simple: Unacknowledge
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
  "11":
    id: "11"
    taskid: 48fc49b0-d56d-413d-8916-52802f51b522
    type: regular
    task:
      id: 48fc49b0-d56d-413d-8916-52802f51b522
      version: -1
      name: canarytools-get-token
      description: Fetch Canary Token file from the Canary Tools server
      script: Thinkst Canary|||canarytools-get-token
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      token:
        complex:
          root: CanaryTools
          accessor: Tokens.CanaryToken
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
  "12":
    id: "12"
    taskid: 0171b57a-9b5e-4e37-861f-8a0d459f251e
    type: condition
    task:
      id: 0171b57a-9b5e-4e37-861f-8a0d459f251e
      version: -1
      name: IsTrue
      description: Check if a given value is true. Will return 'no' otherwise
      scriptName: IsTrue
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "16"
    scriptarguments:
      value:
        simple: ${CanaryTools.IP.Whitelisted}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
    note: false
    timertriggers: []
  "13":
    id: "13"
    taskid: 81fc2198-2175-46cc-8308-3f425573ddaf
    type: condition
    task:
      id: 81fc2198-2175-46cc-8308-3f425573ddaf
      version: -1
      name: Check If token status exists in Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: CanaryTools
                accessor: Tokens.Status
                transformers:
                - operator: atIndex
                  args:
                    index:
                      value:
                        simple: "0"
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "14":
    id: "14"
    taskid: 7b98434c-48a2-41b8-8b86-1f66c521ca02
    type: condition
    task:
      id: 7b98434c-48a2-41b8-8b86-1f66c521ca02
      version: -1
      name: Check Canary Name
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: CanaryTools.Device.Name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "15":
    id: "15"
    taskid: b695b3d6-8bdf-45eb-8d47-96ba20a694de
    type: condition
    task:
      id: b695b3d6-8bdf-45eb-8d47-96ba20a694de
      version: -1
      name: Check Canary ID
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: CanaryTools.Device.ID
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "16":
    id: "16"
    taskid: 2e475711-5989-422e-8c8b-c09a997747d0
    type: regular
    task:
      id: 2e475711-5989-422e-8c8b-c09a997747d0
      version: -1
      name: canarytools-check-whitelist
      description: Check whether a given IP and port are whitelisted
      script: Thinkst Canary|||canarytools-check-whitelist
      type: regular
      iscommand: true
      brand: Thinkst Canary
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      ip:
        simple: 6.6.6.6 # disable-secrets-detection
      port: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
  "19":
    id: "19"
    taskid: 699c80c4-27a5-40e1-8262-182ecc4085ad
    type: title
    task:
      id: 699c80c4-27a5-40e1-8262-182ecc4085ad
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
  "20":
    id: "20"
    taskid: 522940fd-22e0-4fb5-8e40-d9370e5f4646
    type: condition
    task:
      id: 522940fd-22e0-4fb5-8e40-d9370e5f4646
      version: -1
      name: Check if not Whitelisted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CanaryTools.IP.Whitelisted
            iscontext: true
          right:
            value:
              simple: None
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
  "21":
    id: "21"
    taskid: 97d57b7e-4d70-4f5a-839e-279865040107
    type: condition
    task:
      id: 97d57b7e-4d70-4f5a-839e-279865040107
      version: -1
      name: Check Status
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CanaryTools.Alert.Status
            iscontext: true
          right:
            value:
              simple: Acknowledge
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
  "22":
    id: "22"
    taskid: 73d17823-a702-4063-8f0c-1d23b2119624
    type: condition
    task:
      id: 73d17823-a702-4063-8f0c-1d23b2119624
      version: -1
      name: Check Status
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CanaryTools.Alert.Status
            iscontext: true
          right:
            value:
              simple: Acknowledge
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
  "23":
    id: "23"
    taskid: 3126d80e-37f1-4556-8c2b-4da1274f4671
    type: regular
    task:
      id: 3126d80e-37f1-4556-8c2b-4da1274f4671
      version: -1
      name: Test Fetch
      scriptName: FetchFromInstance
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: Thinkst Canary
      expect_data:
        simple: "false"
      instance_name: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {
      "22_23_#default#": 0.89
    },
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
