id: okta_test_playbook
version: -1
fromversion: 3.6.0
name: Okta test playbook
description: Test the functionality of Okta
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: f9fd4278-c268-4e7b-88b4-0c87050f4ef6
    type: start
    task:
      id: f9fd4278-c268-4e7b-88b4-0c87050f4ef6
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": -90
        }
      }
  "2":
    id: "2"
    taskid: e2d5e16e-fc89-4ce7-83ab-0c1daf24340c
    type: regular
    task:
      id: e2d5e16e-fc89-4ce7-83ab-0c1daf24340c
      version: -1
      name: okta-get-group-assignments
      description: Get events for when a user was added to a group.
      script: okta_copy|||okta-get-group-assignments
      type: regular
      iscommand: true
      brand: okta_copy
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      limit: {}
      since: {}
      sortOrder: {}
      until: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": 982
        }
      }
  "5":
    id: "5"
    taskid: 1e97de85-f486-466d-820d-262db3eab501
    type: regular
    task:
      id: 1e97de85-f486-466d-820d-262db3eab501
      version: -1
      name: Verify Context
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: GroupAssignments
      path:
        simple: Okta.Logs
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": 1181
        }
      }
  "7":
    id: "7"
    taskid: 6b6b435f-7e84-4400-800b-b95a4ff00acf
    type: regular
    task:
      id: 6b6b435f-7e84-4400-800b-b95a4ff00acf
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": 78
        }
      }
  "8":
    id: "8"
    taskid: 3afa7830-ed45-41ab-89c2-5404822be98e
    type: regular
    task:
      id: 3afa7830-ed45-41ab-89c2-5404822be98e
      version: -1
      name: okta-get-groups
      description: Get all user groups
      script: okta_copy|||okta-get-groups
      type: regular
      iscommand: true
      brand: okta_copy
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      username:
        simple: test@this.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": 277
        }
      }
  "9":
    id: "9"
    taskid: 77ed9fa7-7c6a-4a93-8244-0c8e408dca25
    type: condition
    task:
      id: 77ed9fa7-7c6a-4a93-8244-0c8e408dca25
      version: -1
      name: Group exists
      description: Check if group exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: string.isEqual
          left:
            value:
              simple: Account.Group.ID
            iscontext: true
          right:
            value:
              simple: 00g8mo0l5wuTxmoIC0h7
    view: |-
      {
        "position": {
          "x": 461,
          "y": 460
        }
      }
  "10":
    id: "10"
    taskid: fb4bae1b-8e80-4ffe-80e5-fb73e2f6a36d
    type: regular
    task:
      id: fb4bae1b-8e80-4ffe-80e5-fb73e2f6a36d
      version: -1
      name: okta-remove-from-group
      description: Removes a user from a group with OKTA_GROUP type.
      script: okta_copy|||okta-remove-from-group
      type: regular
      iscommand: true
      brand: okta_copy
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      groupId:
        simple: 00g8mo0l5wuTxmoIC0h7
      userId:
        simple: ${Account.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 172,
          "y": 659
        }
      }
  "11":
    id: "11"
    taskid: 5ed95bdb-278e-4112-8a48-cc9c2bbae3b2
    type: regular
    task:
      id: 5ed95bdb-278e-4112-8a48-cc9c2bbae3b2
      version: -1
      name: okta-add-to-group
      description: Adds a user to a group with OKTA_GROUP type.
      script: okta_copy|||okta-add-to-group
      type: regular
      iscommand: true
      brand: okta_copy
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      groupId:
        simple: 00g8mo0l5wuTxmoIC0h7
      userId:
        simple: ${Account.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 461,
          "y": 803
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1366,
        "width": 669,
        "x": 172,
        "y": -90
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"