id: ThreatStream-Test
version: -1
name: ThreatStream-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b8132f7d-3c0b-4c7a-8c45-aac5cdef19c9
    type: start
    task:
      id: b8132f7d-3c0b-4c7a-8c45-aac5cdef19c9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 12fd97da-3e35-406d-8afc-1bfe5e0aec64
    type: regular
    task:
      id: 12fd97da-3e35-406d-8afc-1bfe5e0aec64
      version: -1
      name: Check Domain Reputation
      description: Checks the reputation of the domain name.
      script: Anomaliv2|||domain
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      domain:
        simple: dropwellsfargo.com
      include_inactive: {}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 76cdfeca-1cd3-4bf0-8025-8e56c8a97590
    type: condition
    task:
      id: 76cdfeca-1cd3-4bf0-8025-8e56c8a97590
      version: -1
      name: 'Validate  Domain Context '
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.Domain.Address
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.Domain.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 17caeef6-cfc7-43bc-8fd5-434206907c6b
    type: regular
    task:
      id: 17caeef6-cfc7-43bc-8fd5-434206907c6b
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "7"
      - "5"
      - "9"
      - "11"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 59d3583c-ca9d-4db9-86ed-f6bd855d0b8a
    type: regular
    task:
      id: 59d3583c-ca9d-4db9-86ed-f6bd855d0b8a
      version: -1
      name: Check IP Reputation
      description: Checks the reputation of the given IP.
      script: Anomaliv2|||ip
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      include_inactive: {}
      ip:
        simple: 116.101.134.118
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: b71049c5-3f5c-4299-8f3d-6e74d8e35cfd
    type: condition
    task:
      id: b71049c5-3f5c-4299-8f3d-6e74d8e35cfd
      version: -1
      name: Validate IP context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: IP.Address
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.IP.Status
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 05503726-b738-4b17-83d2-d17726044619
    type: regular
    task:
      id: 05503726-b738-4b17-83d2-d17726044619
      version: -1
      name: Check URL reputation
      description: Checks the reputation of the given URL.
      script: Anomaliv2|||url
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      include_inactive: {}
      threshold: {}
      url:
        simple: http://www.myronnhammond.club/godaddy/
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: da4c028b-3382-44bb-8a50-f8a6fa51296a
    type: condition
    task:
      id: da4c028b-3382-44bb-8a50-f8a6fa51296a
      version: -1
      name: Validate URL Reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: URL.Data
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.URL.Status
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 25464c18-4f93-4f1a-8151-2d93ee06496f
    type: regular
    task:
      id: 25464c18-4f93-4f1a-8151-2d93ee06496f
      version: -1
      name: Check email reputation
      description: Checks the reputation of the given email address.
      script: Anomaliv2|||threatstream-email-reputation
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      email:
        simple: tatimouzo1@aliceadsl.fr
      include_inactive: {}
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 15b04bb1-fb80-4992-8fa6-5cebdfd1c44f
    type: condition
    task:
      id: 15b04bb1-fb80-4992-8fa6-5cebdfd1c44f
      version: -1
      name: Validate Email Reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.EmailReputation.Email
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.EmailReputation.Confidence
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 80ac8c57-6bd6-493b-8699-c42fa0381543
    type: regular
    task:
      id: 80ac8c57-6bd6-493b-8699-c42fa0381543
      version: -1
      name: Check MD5 reputation
      description: Checks the reputation of the given md5 of the file.
      script: Anomaliv2|||file
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      include_inactive:
        simple: fal
      md5:
        simple: fc0f4799549242c437cd480c85cb5e16cfdc0c3df622cc31ed9745a45a61df28
      threshold:
        simple: low
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 71ab27e3-73a1-4542-8a08-64b3e077ea56
    type: condition
    task:
      id: 71ab27e3-73a1-4542-8a08-64b3e077ea56
      version: -1
      name: Validate  File reputation
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: File.MD5
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.File.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 49ad2c38-72c5-4ba9-8762-db95a8cada17
    type: regular
    task:
      id: 49ad2c38-72c5-4ba9-8762-db95a8cada17
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 9419b660-de0d-454e-83bf-cde8b4991295
    type: title
    task:
      id: 9419b660-de0d-454e-83bf-cde8b4991295
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 24119a3b-4fc2-48c3-8742-4db4fad7bae0
    type: regular
    task:
      id: 24119a3b-4fc2-48c3-8742-4db4fad7bae0
      version: -1
      name: Get Indicator by ID
      description: Return filtered indicators from ThreatStream. If query is defined,
        it overides all othe arguments that were passed to the command.
      script: Anomaliv2|||threatstream-get-indicators
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      asn: {}
      confidence: {}
      country: {}
      created_ts: {}
      id:
        simple: "51685266655"
      indicator_severity: {}
      indicator_value: {}
      is_public: {}
      limit: {}
      org: {}
      query: {}
      status: {}
      tags_name: {}
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: f2b4d6ae-af0e-4f3b-8245-73b614e2e3d3
    type: condition
    task:
      id: f2b4d6ae-af0e-4f3b-8245-73b614e2e3d3
      version: -1
      name: Validate Indicator Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ThreatStream.Indicators.Value
            iscontext: true
          right:
            value:
              simple: 144.172.153.165
      - - operator: isEqualString
          left:
            value:
              simple: ThreatStream.Indicators.Severity
            iscontext: true
          right:
            value:
              simple: low
      - - operator: isEqualString
          left:
            value:
              simple: ThreatStream.Indicators.Status
            iscontext: true
          right:
            value:
              simple: active
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 154ee7dc-183c-493c-8e4d-4682b12d8400
    type: regular
    task:
      id: 154ee7dc-183c-493c-8e4d-4682b12d8400
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
      - "20"
      - "22"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 0f1cd8cd-9d20-43d8-874b-6a7eaca4a96b
    type: regular
    task:
      id: 0f1cd8cd-9d20-43d8-874b-6a7eaca4a96b
      version: -1
      name: Get Actor list
      description: Returns a list of Threat Model.
      script: '|||threatstream-get-model-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      limit:
        simple: "1"
      model:
        simple: actor
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: ab7c3f26-271a-4a02-80a2-3d834278709d
    type: regular
    task:
      id: ab7c3f26-271a-4a02-80a2-3d834278709d
      version: -1
      name: Get Indicator By Model Actor
      description: Returns a list of indecators associated with the specified model
        and model's id.
      script: Anomaliv2|||threatstream-get-indicators-by-model
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${ThreatStream.List.ID}
      limit:
        simple: "1"
      model:
        simple: actor
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 0a3aceca-03b7-4441-8982-533daaf2d349
    type: regular
    task:
      id: 0a3aceca-03b7-4441-8982-533daaf2d349
      version: -1
      name: Get Passive DNS
      description: Returns enrichment data for Domain or IP for availabe observables.
      script: Anomaliv2|||threatstream-get-passive-dns
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      limit:
        simple: "1"
      type:
        simple: domain
      value:
        simple: eqouifax.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 15f0a4cd-9d28-4d94-8fc1-5898cc800bf2
    type: condition
    task:
      id: 15f0a4cd-9d28-4d94-8fc1-5898cc800bf2
      version: -1
      name: Validate Passive DNS Context
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Domain
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Ip
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Rrtype
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.Source
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.FirstSeen
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: ThreatStream.PassiveDNS.LastSeen
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "22":
    id: "22"
    taskid: 367f00d6-25b2-4fc5-87dd-94f19c379dac
    type: regular
    task:
      id: 367f00d6-25b2-4fc5-87dd-94f19c379dac
      version: -1
      name: Get Campaign List
      description: Returns a list of Threat Model.
      script: Anomaliv2|||threatstream-get-model-list
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      limit:
        simple: "1"
      model:
        simple: campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: 42bee526-f38f-496e-8e55-31d00eed8454
    type: regular
    task:
      id: 42bee526-f38f-496e-8e55-31d00eed8454
      version: -1
      name: Get Indicator By Model Campaing
      description: Returns a list of indecators associated with the specified model
        and model's id.
      script: Anomaliv2|||threatstream-get-indicators-by-model
      type: regular
      iscommand: true
      brand: Anomaliv2
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      id:
        simple: ${ThreatStream.List.ID}
      limit:
        simple: "1"
      model:
        simple: campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
