id: Frontline.Cloud-Test
version: -1
fromversion: 5.0.0
name: Frontline.Cloud-Test
description: This is a test playbook for the Digital Defense Inc. FrontlineVM Integration
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: e86e43e0-38fd-4b62-84c4-f9d4dd6e0d4c
    type: start
    task:
      id: e86e43e0-38fd-4b62-84c4-f9d4dd6e0d4c
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: fe5cc8f6-95fd-4298-8032-a48d5d4f2a4f
    type: regular
    task:
      id: fe5cc8f6-95fd-4298-8032-a48d5d4f2a4f
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: cbe23583-d37e-410f-849b-aa7935b3ea15
    type: regular
    task:
      id: cbe23583-d37e-410f-849b-aa7935b3ea15
      version: -1
      name: frontline-get-assets (get asset that does not exists)
      description: Pull asset that does not exists within Frontline.Cloud
      script: '|||frontline-get-assets'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      hostname: {}
      ip_address:
        simple: 8.8.8.8
      label_name: {}
      max_days_since_scan: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '3':
    id: '3'
    taskid: 700f76bb-4e89-45c7-8c2e-c647457de847
    type: condition
    task:
      id: 700f76bb-4e89-45c7-8c2e-c647457de847
      version: -1
      name: Verify Command Results
      description: Verify command results from task 'frontline-get-assets (get asset
        that does not exits)'.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '8'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isEmpty
          left:
            value:
              simple: FrontlineVM.Hosts
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: 8d64bb4d-a506-4eed-8730-7547144a6599
    type: regular
    task:
      id: 8d64bb4d-a506-4eed-8730-7547144a6599
      version: -1
      name: Close the Investigation
      description: Closing investigation.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '5':
    id: '5'
    taskid: d54829e6-2845-483e-84e9-72bb8a8ec98e
    type: regular
    task:
      id: d54829e6-2845-483e-84e9-72bb8a8ec98e
      version: -1
      name: frontline-get-vulns (get all vulnerabilities)
      description: Pull all vulnerability data from Frontline.Cloud
      script: '|||frontline-get-vulns'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      host_id: {}
      ip_address: {}
      max_days_since_created: {}
      min_days_since_created: {}
      min_severity: {}
      severity: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: 25732b98-143a-47a7-870a-415c1e936987
    type: condition
    task:
      id: 25732b98-143a-47a7-870a-415c1e936987
      version: -1
      name: Verify Command Results
      description: Verify command results from task 'frontline-get-vulns'.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '4'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: FrontlineVM.Vulns
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1255
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '8':
    id: '8'
    taskid: 14336845-da8b-4536-8f76-e0276650b9a5
    type: regular
    task:
      id: 14336845-da8b-4536-8f76-e0276650b9a5
      version: -1
      name: frontline-get-assets (get all assets)
      description: Pull all asset data from Frontline.Cloud
      script: '|||frontline-get-assets'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      hostname: {}
      ip_address: {}
      label_name: {}
      max_days_since_scan: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '9':
    id: '9'
    taskid: 2bcee246-a649-4dec-823b-e04f9e4cc884
    type: condition
    task:
      id: 2bcee246-a649-4dec-823b-e04f9e4cc884
      version: -1
      name: Verify Command Results
      description: Verify command results from task 'frontline-get-assets (get all
        assets)'.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '5'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: FrontlineVM.Hosts
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 905
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1465,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
