id: rsa_packets_and_logs_test
version: -1
name: RSA Packets And Logs test
description: Test RSA P&L integration
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cd2287e1-6e8c-4161-82de-e71999d5b8fb
    type: start
    task:
      id: cd2287e1-6e8c-4161-82de-e71999d5b8fb
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": -413
        }
      }
  "1":
    id: "1"
    taskid: 5a8eb582-ec36-4dbd-8b4b-93c2a2ea462d
    type: regular
    task:
      id: 5a8eb582-ec36-4dbd-8b4b-93c2a2ea462d
      version: -1
      name: netwitness-msearch
      description: Search for pattern matches in many sessions or packets
      script: RSA NetWitness Packets and Logs|||netwitness-msearch
      type: regular
      iscommand: true
      brand: RSA NetWitness Packets and Logs
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      concentratorAddress: {}
      flags:
        simple: regex,sp,si,sm
      limit:
        simple: "1"
      packets: {}
      search:
        simple: ^(.*)
      sessions: {}
      where: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": 204
        }
      }
  "2":
    id: "2"
    taskid: c9ade7fc-9f3e-4bf3-88a6-18b13a89c737
    type: regular
    task:
      id: c9ade7fc-9f3e-4bf3-88a6-18b13a89c737
      version: -1
      name: netwitness-query
      description: Performs a query against the meta database
      script: RSA NetWitness Packets and Logs|||netwitness-query
      type: regular
      iscommand: true
      brand: RSA NetWitness Packets and Logs
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      concentratorAddress: {}
      flags: {}
      id1: {}
      id2: {}
      lastHours: {}
      lastMinutes: {}
      query:
        simple: select * where alias.host contains 'skimresources'
      size:
        simple: "100"
      threshold: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": 436
        }
      }
  "7":
    id: "7"
    taskid: 198e9dc6-c472-471a-8466-80a5dc8747d1
    type: regular
    task:
      id: 198e9dc6-c472-471a-8466-80a5dc8747d1
      version: -1
      name: nw-sdk-values
      description: Performs a value count query and returns the matching values for
        a report
      script: RSA NetWitness Packets and Logs|||nw-sdk-values
      type: regular
      iscommand: true
      brand: RSA NetWitness Packets and Logs
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      aggregateFieldName: {}
      aggregateFunction: {}
      concentratorAddress: {}
      fieldName:
        simple: ip.src
      flags:
        simple: sessions,sort-total,order-ascending
      id1: {}
      id2: {}
      max: {}
      min: {}
      size:
        simple: "20"
      threshold:
        simple: "100000"
      using:
        simple: Concentrator
      where:
        simple: time="2016-Jan-30 13:56:30"-"2018-May-21 12:20:49"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": 649
        }
      }
  "8":
    id: "8"
    taskid: 78e3f682-b83a-4d9f-8114-f6db087ef29d
    type: regular
    task:
      id: 78e3f682-b83a-4d9f-8114-f6db087ef29d
      version: -1
      name: Verify Context
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Events,SearchHits,Values
      path:
        simple: NetWitness
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": 849
        }
      }
  "10":
    id: "10"
    taskid: d76ce703-475e-4448-840c-ed3a98dea371
    type: regular
    task:
      id: d76ce703-475e-4448-840c-ed3a98dea371
      version: -1
      name: Verify Context
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      expectedValue: {}
      fields:
        simple: Node
      path:
        simple: NetWitness
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": 3
        }
      }
  "11":
    id: "11"
    taskid: a0acdda4-0083-4d9a-8df6-e68208a17063
    type: regular
    task:
      id: a0acdda4-0083-4d9a-8df6-e68208a17063
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -13,
          "y": -238
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1357,
        "width": 380,
        "x": -13,
        "y": -413
      }
    }
  }
inputs: []
outputs: []
releaseNotes: "-"
fromversion: "3.5.0"