id: urlscan_malicious_Test
version: -1
name: urlscan_malicious_Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d0575ef2-4421-4988-8d6e-ca54cba5f879
    type: start
    task:
      id: d0575ef2-4421-4988-8d6e-ca54cba5f879
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -232
        }
      }
    note: false
  "3":
    id: "3"
    taskid: c4f7e285-e758-4327-8aeb-51de5f2f7aaa
    type: regular
    task:
      id: c4f7e285-e758-4327-8aeb-51de5f2f7aaa
      version: -1
      name: Check Malicious url
      description: Check if file MD5 is malicious
      script: '|||urlscan-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      url:
        simple: http://malware.wicar.org/data/eicar.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 204
        }
      }
    note: false
  "4":
    id: "4"
    taskid: af5ffda2-df68-48c9-8334-8460471d0502
    type: regular
    task:
      id: af5ffda2-df68-48c9-8334-8460471d0502
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 41
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 9e47f1d3-66e3-4d11-815b-a916da889bc9
    type: condition
    task:
      id: 9e47f1d3-66e3-4d11-815b-a916da889bc9
      version: -1
      name: Get result
      description: Filter context keys by applying one of the various available manipulations
        and storing in a new context key. Please notice that the resulting context
        key will not be available automatically as an option but you can still specify
        it.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    scriptarguments:
      additional: {}
      data: {}
      filter: {}
      filterType: {}
      out: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: URLScan.Domain
            iscontext: true
          right:
            value:
              simple: malware.wicar.org
    view: |-
      {
        "position": {
          "x": 450,
          "y": 369
        }
      }
    note: false
  "8":
    id: "8"
    taskid: ef8d4bdc-c119-4f5b-8334-ae8628dee019
    type: title
    task:
      id: ef8d4bdc-c119-4f5b-8334-ae8628dee019
      version: -1
      name: Malicious
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 595
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 6ec652a3-5300-4871-83e6-1b1a22937d1e
    type: regular
    task:
      id: 6ec652a3-5300-4871-83e6-1b1a22937d1e
      version: -1
      name: Check non-malicious url
      description: Check if file MD5 is malicious
      script: '|||urlscan-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      url:
        simple: https://google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1007,
          "y": 204
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 1244a37a-cba4-4a2f-8582-360db375fbd0
    type: condition
    task:
      id: 1244a37a-cba4-4a2f-8582-360db375fbd0
      version: -1
      name: Get result
      description: Filter context keys by applying one of the various available manipulations
        and storing in a new context key. Please notice that the resulting context
        key will not be available automatically as an option but you can still specify
        it.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    scriptarguments:
      additional: {}
      data: {}
      filter: {}
      filterType: {}
      out: {}
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: URLScan.Domain
            iscontext: true
          right:
            value:
              simple: google.com
    view: |-
      {
        "position": {
          "x": 1007,
          "y": 369
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 2f38abe3-90c3-41c8-88e6-440008088b24
    type: title
    task:
      id: 2f38abe3-90c3-41c8-88e6-440008088b24
      version: -1
      name: Not Malicious
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1007,
          "y": 595
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 9022387e-6d2c-4207-8e37-00bd9061e779
    type: regular
    task:
      id: 9022387e-6d2c-4207-8e37-00bd9061e779
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1007,
          "y": 41
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 892,
        "width": 937,
        "x": 450,
        "y": -232
      }
    }
  }
inputs: []
outputs: []