id: Symantec Messaging Gateway Test
version: -1
name: Symantec Messaging Gateway Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: bfd9179b-1619-400f-8693-5fc8a7bf13e7
    type: start
    task:
      id: bfd9179b-1619-400f-8693-5fc8a7bf13e7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    id: "1"
    taskid: 973dace6-b737-4279-8870-18da86336431
    type: regular
    task:
      id: 973dace6-b737-4279-8870-18da86336431
      version: -1
      name: smg-block-email
      description: Adds email address to the Local Bad Sender Domains.
      script: Symantec Messaging Gateway|||smg-block-email
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      email:
        simple: email@domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    id: "2"
    taskid: b96f7bc1-4828-4c93-802b-c69f90d9c808
    type: regular
    task:
      id: b96f7bc1-4828-4c93-802b-c69f90d9c808
      version: -1
      name: smg-unblock-email
      description: Removes email address from the Local Bad Sender Domains.
      script: Symantec Messaging Gateway|||smg-unblock-email
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      email:
        simple: email@domain.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
  "3":
    id: "3"
    taskid: e25ec9b9-8d46-4457-817c-412a39e10605
    type: regular
    task:
      id: e25ec9b9-8d46-4457-817c-412a39e10605
      version: -1
      name: smg-block-domain
      description: Adds domain to the Local Bad Sender Domains group.
      script: Symantec Messaging Gateway|||smg-block-domain
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      domain:
        simple: www.test.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
  "4":
    id: "4"
    taskid: 40c50201-6556-4a13-83af-d2fabe937ebc
    type: regular
    task:
      id: 40c50201-6556-4a13-83af-d2fabe937ebc
      version: -1
      name: smg-unblock-domain
      description: Removes domain from the Local Bad Sender Domains group.
      script: Symantec Messaging Gateway|||smg-unblock-domain
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      domain:
        simple: www.test.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
  "5":
    id: "5"
    taskid: 5a8ef37a-7709-4da6-8392-2be31230c6bb
    type: regular
    task:
      id: 5a8ef37a-7709-4da6-8392-2be31230c6bb
      version: -1
      name: smg-block-ip
      description: Adds IP address to the Local Bad Sender IPs  group.
      script: Symantec Messaging Gateway|||smg-block-ip
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      ip:
        simple: 10.20.30.40
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
  "7":
    id: "7"
    taskid: 272a4152-38cb-4330-8c9c-0ee63e404e2c
    type: title
    task:
      id: 272a4152-38cb-4330-8c9c-0ee63e404e2c
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
  "8":
    id: "8"
    taskid: c05eaad3-3e33-41ff-81ee-d3303cccf093
    type: regular
    task:
      id: c05eaad3-3e33-41ff-81ee-d3303cccf093
      version: -1
      name: Verify Email Address
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      expectedValue:
        simple: email@domain.com
      fields: {}
      path:
        simple: Email.Address
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "9":
    id: "9"
    taskid: 2c31c4f4-9777-4ff1-8bd5-328fcdd8a596
    type: regular
    task:
      id: 2c31c4f4-9777-4ff1-8bd5-328fcdd8a596
      version: -1
      name: Verify Blocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      expectedValue:
        simple: "true"
      fields: {}
      path:
        simple: Email.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
  "10":
    id: "10"
    taskid: c54b0359-c5bc-4182-8244-d4c953997458
    type: regular
    task:
      id: c54b0359-c5bc-4182-8244-d4c953997458
      version: -1
      name: Verify Unblocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue:
        simple: "false"
      fields: {}
      path:
        simple: Email.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
  "11":
    id: "11"
    taskid: 90aa81c6-5958-4606-8be9-d93217762939
    type: regular
    task:
      id: 90aa81c6-5958-4606-8be9-d93217762939
      version: -1
      name: Verify Domain
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      expectedValue:
        simple: www.test.com
      fields: {}
      path:
        simple: Domain.Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
  "12":
    id: "12"
    taskid: 8630aa83-16c4-41e6-8f0c-ec7a760b8e42
    type: regular
    task:
      id: 8630aa83-16c4-41e6-8f0c-ec7a760b8e42
      version: -1
      name: Verify Blocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      expectedValue:
        simple: "true"
      fields: {}
      path:
        simple: Domain.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
  "13":
    id: "13"
    taskid: 0728f51f-14d5-4bbc-8a84-306dff812297
    type: regular
    task:
      id: 0728f51f-14d5-4bbc-8a84-306dff812297
      version: -1
      name: Verify Unblocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      expectedValue:
        simple: "false"
      fields: {}
      path:
        simple: Domain.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
  "14":
    id: "14"
    taskid: e833a81d-7e80-4706-8bf6-b603e0ba2be1
    type: regular
    task:
      id: e833a81d-7e80-4706-8bf6-b603e0ba2be1
      version: -1
      name: Verify IP Address
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      expectedValue:
        simple: 10.20.30.40
      fields: {}
      path:
        simple: IP.Address
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
  "15":
    id: "15"
    taskid: 6169db6d-73fd-48bd-86c5-4926f93b3c7f
    type: regular
    task:
      id: 6169db6d-73fd-48bd-86c5-4926f93b3c7f
      version: -1
      name: Verify Blocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      expectedValue:
        simple: "true"
      fields: {}
      path:
        simple: IP.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
  "16":
    id: "16"
    taskid: ebf39e3d-2862-479f-870f-df0fc50dbb5d
    type: regular
    task:
      id: ebf39e3d-2862-479f-870f-df0fc50dbb5d
      version: -1
      name: Verify Unblocked
      description: |-
        Verifies path in context:
        - Verifies path existence
        - If matching object is an array: verify fields exists in each of the objects in the array
        - If matching object is not an array: verify fields exists in matching object
        - if 'expectedValue' is given: ensure that the given value is equal to the context path
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      expectedValue:
        simple: "false"
      fields: {}
      path:
        simple: IP.Blocked
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
  "17":
    id: "17"
    taskid: d38c911c-04ee-4f41-82e0-7005bc8e2e41
    type: regular
    task:
      id: d38c911c-04ee-4f41-82e0-7005bc8e2e41
      version: -1
      name: smg-unblock-ip
      description: Removes IP address from the Local Bad Sender IPs  group.
      script: Symantec Messaging Gateway|||smg-unblock-ip
      type: regular
      iscommand: true
      brand: Symantec Messaging Gateway
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      ip:
        simple: 10.20.30.40
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2835,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
