id: Palo Alto Networks Cortex Test
version: -1
name: Palo Alto Networks Cortex Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 459137f7-cf03-450e-87d2-94cec22b590d
    type: start
    task:
      id: 459137f7-cf03-450e-87d2-94cec22b590d
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": -170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: b4056e07-be74-4f27-8514-dcdbc5700a6f
    type: regular
    task:
      id: b4056e07-be74-4f27-8514-dcdbc5700a6f
      version: -1
      name: Query Logs
      description: Query Cortex Logging service
      script: '|||cortex-query-logs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      endTime: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 0d4f433b-00ef-445e-8460-3719365cd961
    type: condition
    task:
      id: 0d4f433b-00ef-445e-8460-3719365cd961
      version: -1
      name: Verify Query Logs Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
      - "9"
      - "11"
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.id
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.score
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.action
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.app
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.dst
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.rule
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.src
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.category-of-app
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.srcloc
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.dstloc
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.characteristic-of-app
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.device_name
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.nat
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.natdport
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.natdst
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: Cortex.Logging.natsrc
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: f87c9945-4496-47b8-8655-059ecc878341
    type: title
    task:
      id: f87c9945-4496-47b8-8655-059ecc878341
      version: -1
      name: Success
      description: Query Cortex Logging service according to pre-set queries
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 57bc1e0a-2b44-4b32-8db5-48c4f57407a1
    type: regular
    task:
      id: 57bc1e0a-2b44-4b32-8db5-48c4f57407a1
      version: -1
      name: Fetch events
      description: Execute FetchIncident for a given instance
      scriptName: FetchFromInstance
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: Palo Alto Networks Cortex
      expect_data: {}
      instance_name: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1045
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 3e01dc08-f22a-4916-83f3-7f49eb5aeeee
    type: regular
    task:
      id: 3e01dc08-f22a-4916-83f3-7f49eb5aeeee
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 0dbc00b5-9ce6-4cb0-819f-0e74fb784bdd
    type: regular
    task:
      id: 0dbc00b5-9ce6-4cb0-819f-0e74fb784bdd
      version: -1
      name: cortex-query-threat-logs
      description: TBD
      script: Palo Alto Networks Cortex|||cortex-query-threat-logs
      type: regular
      iscommand: true
      brand: Palo Alto Networks Cortex
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      action: {}
      endTime: {}
      fields: {}
      from_zone: {}
      hash: {}
      ip: {}
      port: {}
      query: {}
      rangeValue: {}
      rule: {}
      startTime: {}
      timeRange: {}
      to_zone: {}
      url: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: f8b6e4df-1071-4a47-8dbd-409ef09fb9a0
    type: condition
    task:
      id: f8b6e4df-1071-4a47-8dbd-409ef09fb9a0
      version: -1
      name: Verify Query Threat Logs Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Cortex
                accessor: Logging.Threat.Src
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 725
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: cca21371-284c-469a-864f-81ad1b536f14
    type: regular
    task:
      id: cca21371-284c-469a-864f-81ad1b536f14
      version: -1
      name: cortex-query-traffic-logs
      description: TBD
      script: Palo Alto Networks Cortex|||cortex-query-traffic-logs
      type: regular
      iscommand: true
      brand: Palo Alto Networks Cortex
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      action: {}
      endTime: {}
      fields: {}
      from_zone: {}
      ip: {}
      port: {}
      query: {}
      rangeValue: {}
      rule: {}
      startTime: {}
      timeRange: {}
      to_zone: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 90960bf2-89bb-4239-8153-e5e12de6432d
    type: condition
    task:
      id: 90960bf2-89bb-4239-8153-e5e12de6432d
      version: -1
      name: Verify Query Traffic Logs Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Cortex
                accessor: Logging.Traffic.Src
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 725
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: f8aec994-140c-4380-8a27-8fe33c9cff76
    type: regular
    task:
      id: f8aec994-140c-4380-8a27-8fe33c9cff76
      version: -1
      name: cortex-query-traps-logs
      description: TBD
      script: Palo Alto Networks Cortex|||cortex-query-traps-logs
      type: regular
      iscommand: true
      brand: Palo Alto Networks Cortex
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      category: {}
      endTime: {}
      fields: {}
      hash: {}
      host: {}
      ip: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
      user: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: eaad556a-f3e2-48da-8df0-3d7ef7f62935
    type: regular
    task:
      id: eaad556a-f3e2-48da-8df0-3d7ef7f62935
      version: -1
      name: cortex-query-analytics-logs
      description: TBD
      script: Palo Alto Networks Cortex|||cortex-query-analytics-logs
      type: regular
      iscommand: true
      brand: Palo Alto Networks Cortex
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      category: {}
      endTime: {}
      fields: {}
      hash: {}
      host: {}
      ip: {}
      query: {}
      rangeValue: {}
      startTime: {}
      timeRange: {}
      user: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -370,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: e1105989-382e-4665-8de4-a9ff1a3806b3
    type: condition
    task:
      id: e1105989-382e-4665-8de4-a9ff1a3806b3
      version: -1
      name: Verify Query Traps Logs Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Cortex
                accessor: Logging.Traps.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 725
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: d9357ada-7506-40cc-8b27-19f8e6dfebe4
    type: condition
    task:
      id: d9357ada-7506-40cc-8b27-19f8e6dfebe4
      version: -1
      name: Verify Query Analytics Logs Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Cortex
                accessor: Logging.Analytics.Severity
            iscontext: true
    view: |-
      {
        "position": {
          "x": -370,
          "y": 725
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1455,
        "width": 1660,
        "x": -370,
        "y": -170
      }
    }
  }
inputs: []
outputs: []
