id: hashicorp_test
version: -1
name: hashicorp_test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e26c1a8a-a9f2-4b21-886d-39eb298181c9
    type: start
    task:
      id: e26c1a8a-a9f2-4b21-886d-39eb298181c9
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: d8caa391-a351-42c5-8cbc-db60e34113bb
    type: regular
    task:
      id: d8caa391-a351-42c5-8cbc-db60e34113bb
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: da89ff6b-99e7-4da7-8d94-4e0e6886b75a
    type: regular
    task:
      id: da89ff6b-99e7-4da7-8d94-4e0e6886b75a
      version: -1
      name: hashicorp-list-secrets-engines
      script: HashiCorp Vault|||hashicorp-list-secrets-engines
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: a3294a19-669b-46f9-8b41-8fcd19d8f4b6
    type: regular
    task:
      id: a3294a19-669b-46f9-8b41-8fcd19d8f4b6
      version: -1
      name: hashicorp-list-secrets
      script: HashiCorp Vault|||hashicorp-list-secrets
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      engine:
        complex:
          root: HashiCorp
          accessor: Engine
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: secret/
              field:
                value:
                  simple: Path
              getField:
                value:
                  simple: Path
      version:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 6e59529d-96ea-4763-88bf-774ab9a08fd6
    type: regular
    task:
      id: 6e59529d-96ea-4763-88bf-774ab9a08fd6
      version: -1
      name: hashicorp-get-secret-metadata
      script: HashiCorp Vault|||hashicorp-get-secret-metadata
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      engine_path:
        simple: secret/
      secret_path:
        complex:
          root: HashiCorp
          accessor: Secret
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: test_secret
              field:
                value:
                  simple: Path
              getField:
                value:
                  simple: Path
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 505a18a3-7728-4862-8f47-35e3fe643df5
    type: condition
    task:
      id: 505a18a3-7728-4862-8f47-35e3fe643df5
      version: -1
      name: Is deleted
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: HashiCorp
                accessor: Secret.Version
                transformers:
                - operator: WhereFieldEquals
                  args:
                    equalTo:
                      value:
                        simple: "2"
                    field:
                      value:
                        simple: Number
                    getField:
                      value:
                        simple: Deleted
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: ba770892-244b-4fa0-890c-bd26bdb8a323
    type: regular
    task:
      id: ba770892-244b-4fa0-890c-bd26bdb8a323
      version: -1
      name: hashicorp-undelete-secret
      script: HashiCorp Vault|||hashicorp-undelete-secret
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      engine_path:
        simple: secret/
      secret_path:
        simple: test_secret
      versions:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 335f6eff-a46f-420c-88aa-8063672f178b
    type: regular
    task:
      id: 335f6eff-a46f-420c-88aa-8063672f178b
      version: -1
      name: hashicorp-delete-secret
      script: HashiCorp Vault|||hashicorp-delete-secret
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      engine_path:
        simple: secret/
      secret_path:
        simple: test_secret
      versions:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 05c1d2ab-e3ff-4c10-8cdd-e477eca1d79c
    type: regular
    task:
      id: 05c1d2ab-e3ff-4c10-8cdd-e477eca1d79c
      version: -1
      name: hashicorp-undelete-secret
      script: HashiCorp Vault|||hashicorp-undelete-secret
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      engine_path:
        simple: secret/
      secret_path:
        simple: test_secret
      versions:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 83c352e1-c14b-43f6-8969-f13d444363be
    type: regular
    task:
      id: 83c352e1-c14b-43f6-8969-f13d444363be
      version: -1
      name: hashicorp-destroy-secret
      script: HashiCorp Vault|||hashicorp-destroy-secret
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      engine_path:
        simple: secret/
      secret_path:
        simple: test_secret
      versions:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: d1e40572-6a52-41e5-83a0-0f37eb397c6e
    type: regular
    task:
      id: d1e40572-6a52-41e5-83a0-0f37eb397c6e
      version: -1
      name: hashicorp-enable-engine
      script: HashiCorp Vault|||hashicorp-enable-engine
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      audit_non_hmac_request_keys: {}
      audit_non_hmac_response_keys: {}
      default_lease_ttl: {}
      description: {}
      force_no_cache: {}
      kv_version: {}
      listing_visibility: {}
      local: {}
      max_lease_ttl: {}
      passthrough_request_headers: {}
      path:
        simple: 'test_${TimeNowUnix} '
      seal_wrap: {}
      type:
        simple: kv
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 08fae6fb-943a-4381-8966-c46a884b2820
    type: regular
    task:
      id: 08fae6fb-943a-4381-8966-c46a884b2820
      version: -1
      name: hashicorp-disable-engine
      script: HashiCorp Vault|||hashicorp-disable-engine
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      path:
        simple: test_${TimeNowUnix} /
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: e687c631-b4eb-4ba1-85f0-15b547f7513e
    type: regular
    task:
      id: e687c631-b4eb-4ba1-85f0-15b547f7513e
      version: -1
      name: hashicorp-list-policies
      script: HashiCorp Vault|||hashicorp-list-policies
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 801af8f1-fc76-4602-8b6e-6b11015e7a0b
    type: regular
    task:
      id: 801af8f1-fc76-4602-8b6e-6b11015e7a0b
      version: -1
      name: hashicorp-get-policy
      description: Get information for a policy
      script: '|||hashicorp-get-policy'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      name:
        complex:
          root: HashiCorp
          accessor: Policy
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: default
              field:
                value:
                  simple: Name
              getField:
                value:
                  simple: Name
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: c742646b-b21d-43e9-802f-aef8ad5e0ef0
    type: regular
    task:
      id: c742646b-b21d-43e9-802f-aef8ad5e0ef0
      version: -1
      name: hashicorp-create-token
      script: HashiCorp Vault|||hashicorp-create-token
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      display_name:
        simple: test
      explicit_max_ttl: {}
      meta: {}
      no_default_policy: {}
      no_parent: {}
      num_uses: {}
      period: {}
      policies:
        simple: ${HashiCorp.Policy.Name}
      renewable: {}
      role_name:
        simple: test
      ttl:
        simple: 10m
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 1c9f3549-d0ee-4c2d-8b62-b7dcf7ea570d
    type: regular
    task:
      id: 1c9f3549-d0ee-4c2d-8b62-b7dcf7ea570d
      version: -1
      name: hashicorp-configure-engine
      script: HashiCorp Vault|||hashicorp-configure-engine
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      path:
        simple: secret/
      type:
        simple: kv
      version:
        simple: "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: ade8806b-6c71-4c6e-84eb-2270446828b4
    type: regular
    task:
      id: ade8806b-6c71-4c6e-84eb-2270446828b4
      version: -1
      name: GetTime
      description: |
        Retrieves the current date and time.
      scriptName: GetTime
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      contextKey: {}
      date: {}
      dateFormat: {}
      hoursAgo: {}
      minutesAgo: {}
      monthsAgo: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: a6814aa4-b7c8-437a-8558-2598341b864a
    type: regular
    task:
      id: a6814aa4-b7c8-437a-8558-2598341b864a
      version: -1
      name: hashicorp-reset-configuration
      script: HashiCorp Vault|||hashicorp-reset-configuration
      type: regular
      iscommand: true
      brand: HashiCorp Vault
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3040,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
