id: ExtractDomainFromUrlAndEmail-Test
version: -1
name: ExtractDomainFromUrlAndEmail-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d039c7dd-40cc-4bdb-814a-2bb4b4757334
    type: start
    task:
      id: d039c7dd-40cc-4bdb-814a-2bb4b4757334
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: f18a907d-0273-4b45-87f3-a7d6c017d0bd
    type: regular
    task:
      id: f18a907d-0273-4b45-87f3-a7d6c017d0bd
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 02289f6f-d151-4a58-8114-0b71b06748ee
    type: regular
    task:
      id: 02289f6f-d151-4a58-8114-0b71b06748ee
      version: -1
      name: ExtractDomainFromUrlAndEmail - test single input
      description: Extract Domain from a URL or Email
      scriptName: ExtractDomainFromUrlAndEmail
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      input:
        simple: example@hotmail.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 9fce557e-90fd-451f-84de-16595b303cf9
    type: regular
    task:
      id: 9fce557e-90fd-451f-84de-16595b303cf9
      version: -1
      name: VerifyHumanReadableContains
      description: Verify given entry contains a string
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: hotmail.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 1aab68d7-4517-4e7b-8ab1-473ffbbc332b
    type: title
    task:
      id: 1aab68d7-4517-4e7b-8ab1-473ffbbc332b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 83112962-cf22-4c3c-859d-fbce865eb4ef
    type: regular
    task:
      id: 83112962-cf22-4c3c-859d-fbce865eb4ef
      version: -1
      name: ExtractDomainFromUrlAndEmail - test multiple input
      description: Extract Domain from a URL or Email
      scriptName: ExtractDomainFromUrlAndEmail
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
      - "7"
    scriptarguments:
      input:
        simple: https://typora.io/, example@macmillan.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 5ad94d37-1c36-4a73-8712-cb08d4ac1e11
    type: regular
    task:
      id: 5ad94d37-1c36-4a73-8712-cb08d4ac1e11
      version: -1
      name: VerifyHumanReadableContains
      description: Verify given entry contains a string
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
      substring:
        simple: typora.io # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: ae88e9c4-1922-45b7-8a70-323acc35eaad
    type: regular
    task:
      id: ae88e9c4-1922-45b7-8a70-323acc35eaad
      version: -1
      name: VerifyHumanReadableContains
      description: Verify given entry contains a string
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "1"
      substring:
        simple: macmillan.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 1240,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
