id: HybridAnalysis-Test
version: -1
name: HybridAnalysis-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b2d70110-f597-4f63-8f7f-c62350b38c1f
    type: start
    task:
      id: b2d70110-f597-4f63-8f7f-c62350b38c1f
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 705c8f95-d80e-4260-8201-e3218c24db3d
    type: regular
    task:
      id: 705c8f95-d80e-4260-8201-e3218c24db3d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 0913b524-b5c7-464d-8873-c14fa44d93f0
    type: playbook
    task:
      id: 0913b524-b5c7-464d-8873-c14fa44d93f0
      version: -1
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: HybridAnalysis
          accessor: URL.ID
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: ID
      PollingCommandName:
        simple: hybrid-analysis-quick-scan-url-results
      Timeout:
        simple: "10"
      dt:
        simple: HybridAnalysis.URL(val.Finished != 'true').ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: d4315d15-5eac-4619-82a9-b9b3605b5cab
    type: regular
    task:
      id: d4315d15-5eac-4619-82a9-b9b3605b5cab
      version: -1
      name: hybrid-analysis-quick-scan-url
      description: Scan a url for analysis
      script: '|||hybrid-analysis-quick-scan-url'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      scan_type: {}
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: fbe56d92-ec38-4117-84bf-cbcee07f9616
    type: title
    task:
      id: fbe56d92-ec38-4117-84bf-cbcee07f9616
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 2d584458-e17c-453d-8307-5086b4490b3b
    type: regular
    task:
      id: 2d584458-e17c-453d-8307-5086b4490b3b
      version: -1
      name: hybrid-analysis-scan
      description: Get summary information for a given MD5, SHA1 or SHA256 and all
        the reports generated for any environment ID
      script: '|||hybrid-analysis-scan'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      file:
        simple: dd014af5ed6b38d9130e3f466f850e46d21b951199d53a18ef29ee9341614eaf
      malicious_threat_levels: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 35b5e8e3-51a9-48a0-809e-29a608bfbccf
    type: condition
    task:
      id: 35b5e8e3-51a9-48a0-809e-29a608bfbccf
      version: -1
      name: verify-scan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: DBotScore
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Vendor
            iscontext: true
          right:
            value:
              simple: Hybrid Analysis
      - - operator: isEqualString
          left:
            value:
              simple: File.SHA1
            iscontext: true
          right:
            value:
              simple: 0032c5e2337370e1db1ba5aa5af93685937cbb81
      - - operator: isEqualString
          left:
            value:
              simple: File.submitname
            iscontext: true
          right:
            value:
              simple: http://www.google.com/
      - - operator: isEqualNumber
          left:
            value:
              simple: File.environmentId
            iscontext: true
          right:
            value:
              simple: "120"
    view: |-
      {
        "position": {
          "x": 152.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 78c79b9c-ca7b-4852-8265-b0762a6350e8
    type: regular
    task:
      id: 78c79b9c-ca7b-4852-8265-b0762a6350e8
      version: -1
      name: hybrid-analysis-submit-url-for-analysis
      description: Submit a url for analysis
      script: '|||hybrid-analysis-submit-url-for-analysis'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      environmentID:
        simple: "100"
      url:
        simple: www.google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 21e15bba-3e7a-495d-8c29-c41f89520449
    type: regular
    task:
      id: 21e15bba-3e7a-495d-8c29-c41f89520449
      version: -1
      name: verify submission through scan
      description: Get summary information for a given MD5, SHA1 or SHA256 and all
        the reports generated for any environment ID
      script: '|||hybrid-analysis-scan'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      file:
        simple: ${HybridAnalysis.Submit.SHA256}
      malicious_threat_levels: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 415817ca-d2ce-46e4-8b0f-ce855fd9d588
    type: condition
    task:
      id: 415817ca-d2ce-46e4-8b0f-ce855fd9d588
      version: -1
      name: verify submission scan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: File.SHA256
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: dede989a-6d42-44de-8c98-2d02633adf95
    type: regular
    task:
      id: dede989a-6d42-44de-8c98-2d02633adf95
      version: -1
      name: hybrid-analysis-search
      description: Search the database using the Hybrid Analysis search syntax
      script: '|||hybrid-analysis-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      authentihash: {}
      av_detect: {}
      context: {}
      country: {}
      domain: {}
      env_id: {}
      filename:
        simple: test.exe
      filetype: {}
      filetype_desc: {}
      host: {}
      imp_hash: {}
      min_malicious_scanners: {}
      port: {}
      query: {}
      similar_to: {}
      ssdeep: {}
      tag: {}
      url: {}
      verdict: {}
      vx_family: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: d6d16cd8-f9d5-4797-8aad-725071e28700
    type: condition
    task:
      id: d6d16cd8-f9d5-4797-8aad-725071e28700
      version: -1
      name: verify-search
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Indicator
            iscontext: true
          right:
            value:
              simple: test.exe
      - - operator: isEqualString
          left:
            value:
              simple: DBotScore.Score
            iscontext: true
          right:
            value:
              simple: "3"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "12_3_yes": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1960,
        "width": 707.5,
        "x": 152.5,
        "y": 50
      }
    }
  }
inputs: []
outputs: []