id: StixCreator-Test
version: -1
name: StixCreator-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 836efd42-b9a2-409d-8979-099a1dd7ad73
    type: start
    task:
      id: 836efd42-b9a2-409d-8979-099a1dd7ad73
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: e50d117c-df8b-44c2-87ba-906ed0625623
    type: regular
    task:
      id: e50d117c-df8b-44c2-87ba-906ed0625623
      version: -1
      name: Stix2Creator with Email
      scriptName: StixCreator
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      doubleBackslash: {}
      indicators:
        simple: |-
          {"0": {"firstSeen": "2019-03-13T11:39:11+02:00", "id": "320", "indicator_type":
                    "Email", "investigationIDs": "101, 128, 237, 283, 343, 462, 466", "lastSeen":
                    "2019-03-25T17:08:25+02:00", "source": "DBot", "timestamp": "2019-03-13T11:39:11+02:00",
                    "value": "koko@demisto.com"}}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 45693cf4-7a89-42e8-8c28-259e09e9624b
    type: condition
    task:
      id: 45693cf4-7a89-42e8-8c28-259e09e9624b
      version: -1
      name: Check STIX Export Result
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: StixExportedIndicators.pattern
            iscontext: true
          right:
            value:
              simple: '[email-message:sender_ref.value = ''koko@demisto.com'']'
    view: |-
      {
        "position": {
          "x": 450,
          "y": 440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: f841d097-00eb-403e-8168-799cd6f3ac0c
    type: title
    task:
      id: f841d097-00eb-403e-8168-799cd6f3ac0c
      version: -1
      name: Success
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 073ee3b1-687b-4e73-8c8c-d24e1fdb228b
    type: regular
    task:
      id: 073ee3b1-687b-4e73-8c8c-d24e1fdb228b
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 7c729ae3-0b1d-4f96-8693-925524d75044
    type: regular
    task:
      id: 7c729ae3-0b1d-4f96-8693-925524d75044
      version: -1
      name: Stix2Creator with IP
      scriptName: StixCreator
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      doubleBackslash: {}
      indicators:
        simple: |-
          {"0": {"firstSeen": "2019-03-13T12:06:20+02:00", "id": "994", "indicator_type":
                    "IP", "investigationIDs": "237, 283, 466", "lastSeen": "2019-03-24T10:33:42+02:00",
                    "score": "Bad", "source": "DBot", "timestamp": "2019-03-13T12:06:27+02:00",
                    "value": "1.2.3.4"}}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 41dd7376-9b63-410b-881b-69daa8628a34
    type: condition
    task:
      id: 41dd7376-9b63-410b-881b-69daa8628a34
      version: -1
      name: Check STIX Export Result
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: StixExportedIndicators.pattern
            iscontext: true
          right:
            value:
              simple: '[ipv4-addr:value = ''1.2.3.4'']'
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "2_4_yes": 0.39
    },
    "paper": {
      "dimensions": {
        "height": 1205,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
