id: Splunk-Test
version: -1
contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
name: Splunk-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: "153"
    type: start
    task:
      id: "153"
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: "162"
    type: regular
    task:
      id: "162"
      version: -1
      name: splunk-search
      description: Searches Splunk for events.
      script: '|||splunk-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      app: {}
      batch_limit: {}
      earliest_time:
        simple: -1000d
      event_limit: {}
      latest_time: {}
      query:
        simple: '* | head 3'
      update_context: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: "147"
    type: regular
    task:
      id: "147"
      version: -1
      name: Verify Context result of Splunk Search
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: ${Splunk.Result}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: "161"
    type: regular
    task:
      id: "161"
      version: -1
      name: Get indexes names
      description: Prints all Splunk index names.
      script: '|||splunk-get-indexes'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      extend-context:
        simple: indexes=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: "141"
    type: condition
    task:
      id: "141"
      version: -1
      name: Has main index
      scriptName: StringContains
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "7"
      "yes":
      - "5"
    scriptarguments:
      left: {}
      right: {}
      string:
        simple: ${JsonStr}
      substring:
        simple: main
      substringSeperator: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "5":
    id: "5"
    taskid: "165"
    type: regular
    task:
      id: "165"
      version: -1
      name: Create new Splunk event
      description: Creates a new event in Splunk.
      script: '|||splunk-submit-event'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      data:
        simple: test
      host:
        simple: localhost
      index:
        simple: main
      sourcetype:
        simple: demisto-ci
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "6":
    id: "6"
    taskid: "137"
    type: regular
    task:
      id: "137"
      version: -1
      name: DumpJSON
      description: Dumps a json from context key input, and returns a json object
        string result
      scriptName: DumpJSON
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      extend-context: {}
      key:
        simple: indexes
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "7":
    id: "7"
    taskid: "142"
    type: regular
    task:
      id: "142"
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "8":
    id: "8"
    taskid: "163"
    type: regular
    task:
      id: "163"
      version: -1
      name: Test eventcount query
      description: Searches Splunk for events.
      script: '|||splunk-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      app: {}
      batch_limit: {}
      earliest_time: {}
      event_limit: {}
      latest_time: {}
      query:
        simple: '| eventcount'
      update_context: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "9":
    id: "9"
    taskid: "143"
    type: condition
    task:
      id: "143"
      version: -1
      name: Verify eventcount
      scriptName: IsGreaterThan
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "11"
      "yes":
      - "12"
    scriptarguments:
      first:
        simple: ${eventcount.[0].count}
      second:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "10":
    id: "10"
    taskid: "150"
    type: regular
    task:
      id: "150"
      version: -1
      name: Hurry!
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Hurry!
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "11":
    id: "11"
    taskid: "138"
    type: regular
    task:
      id: "138"
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "12":
    id: "12"
    taskid: "151"
    type: title
    task:
      id: "151"
      version: -1
      name: Test _raw parsing
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "13":
    id: "13"
    taskid: "166"
    type: regular
    task:
      id: "166"
      version: -1
      name: Parse Raw
      description: Parses the raw part of the event.
      script: '|||splunk-parse-raw'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      raw: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "14":
    id: "14"
    taskid: "139"
    type: regular
    task:
      id: "139"
      version: -1
      name: Verify parse get's to context
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: Splunk.Raw.Parsed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "15":
    id: "15"
    taskid: "152"
    type: regular
    task:
      id: "152"
      version: -1
      name: Add raw Data example
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      append: {}
      key:
        simple: rawEvent
      value:
        simple: 1531041382, search_name="0 - Azure AD-Concurrent Access From Different
          GEO", logon_ip="xx.xx.xx.xx", logon_ip="xx.xx.xx.xx", logon_ip="xx.xx.xx.xx",
          logon_source_Country="Egypt", logon_source_Country="Germany", logon_source_info="Potentially_unauthorized",
          logon_source_info="VPN", timestamps="2018-07-08T08:22:41", timestamps="2018-07-08T08:28:50",
          timestamps="2018-07-08T08:35:31", country_count="2", country_in_AD="United
          Arab Emirates", info_max_time="+Infinity", info_min_time="0.000", muid="xx.xx.xx.xx",
          service="AzureActiveDirectory", user="xx.xx.xx.xx", user_type="A regular
          user", users_bunit="xx.xx.xx.xx"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "16":
    id: "16"
    taskid: "164"
    type: regular
    task:
      id: "164"
      version: -1
      name: Parse Raw example
      description: Parses the raw part of the event.
      script: '|||splunk-parse-raw'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      raw:
        simple: ${rawEvent}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": 2300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "17":
    id: "17"
    taskid: "167"
    type: condition
    task:
      id: "167"
      version: -1
      name: Is Raw parsed ?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "18"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Splunk.Raw.Parsed
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "18":
    id: "18"
    taskid: "168"
    type: regular
    task:
      id: "168"
      version: -1
      name: FAIL
      scriptName: VerifyContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      expectedValue: {}
      fields: {}
      path:
        simple: non-existent
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2690,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
