id: UnEscapeURL-Test
version: -1
name: UnEscapeURL-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 039c2f4a-257d-40d0-8f4b-e94440942237
    type: start
    task:
      id: 039c2f4a-257d-40d0-8f4b-e94440942237
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 9628f06e-6df0-4379-8205-c8ab212d9447
    type: regular
    task:
      id: 9628f06e-6df0-4379-8205-c8ab212d9447
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "4"
      - "9"
      - "10"
      - "15"
      - "17"
      - "20"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 2c6b763e-c7c7-413b-800a-28298fc072cc
    type: regular
    task:
      id: 2c6b763e-c7c7-413b-800a-28298fc072cc
      version: -1
      name: UnescapeUrl
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v2/url?u=http-3A__go.getpostman.com_y4wULsdG0h0DDMY0Dv00100&d=DwMFaQ&c=ywDJJevdGcjv4rm9P3FcNg&r=s5kA2oIAQRXsacJiBKmTORIWyRN39ZKhobje2GyRgNs&m=vN1dVSiZvEoM9oExtQqEptm9Dbvq9tnjACDZzrBLaWI&s=zroN7KQdBCPBOfhOmv5SP1DDzZKZ1y9I3x4STS5PbHA&e= # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 465c3d29-eddd-4838-84d4-5d1c4784e4a7
    type: regular
    task:
      id: 465c3d29-eddd-4838-84d4-5d1c4784e4a7
      version: -1
      name: UnEscapeUrl
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v2/url?u=http-3A__maokvo.eu&d=DwMFAg&c=o6x-uYg5urBaLMPPRuq64I5b6ZOFWaPdobkZ8TbBW7M&r=0dtZ_EttZY1gHOgGdV-z-dFmoGOY7zdlOVi7L2EIj14&m=xskGZ0jNEJDRYL6ypuSoCj4YX6FMH8DqJ2l2jNxFL6I&s=KqZlmY1ZrCNVyIId8ADYgiCYNpzbB7-qmlmzv-KqYMs&e= # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: de491741-2d76-431e-849d-ab3adfed7d94
    type: regular
    task:
      id: de491741-2d76-431e-849d-ab3adfed7d94
      version: -1
      name: Check Url
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://go.getpostman.com/y4wULsdG0h0DDMY0Dv00100 # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 52b25bc3-1961-482b-822a-13852f23a360
    type: title
    task:
      id: 52b25bc3-1961-482b-822a-13852f23a360
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 7d6288a4-f20b-42cc-83cf-714dfb160e56
    type: regular
    task:
      id: 7d6288a4-f20b-42cc-83cf-714dfb160e56
      version: -1
      name: Check Url
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://maokvo.eu # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 62da15b5-019a-400f-8262-ae4a983037e6
    type: regular
    task:
      id: 62da15b5-019a-400f-8262-ae4a983037e6
      version: -1
      name: UnEscapeURL - ATP Safelink
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      input:
        simple: na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.avanan.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 82510bf8-3a95-45d1-8109-6e0179245389
    type: regular
    task:
      id: 82510bf8-3a95-45d1-8109-6e0179245389
      version: -1
      name: UnEscapeURL - ATP Safelink
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      input:
        simple: https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FPhilipsBeLux&data=02|01||cb2462dc8640484baf7608d638d2a698|1a407a2d76754d178692b3ac285306e4|0|0|636758874714819880&sdata=dnJiphWFhnAKsk5Ps0bj0p%2FvXVo8TpidtGZcW6t8lDQ%3D&reserved=0%3E%5bcid:image003.gif@01CF4D7F.1DF62650%5d%3C # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: a3d94779-c273-4c54-8c40-c00be9926dcb
    type: regular
    task:
      id: a3d94779-c273-4c54-8c40-c00be9926dcb
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://www.avanan.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: a1464036-6807-42d3-876f-fcedeaa3a293
    type: regular
    task:
      id: a1464036-6807-42d3-876f-fcedeaa3a293
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: https://twitter.com/PhilipsBeLux # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: b5ac93ea-c625-4e44-862a-df43ebc242ea
    type: regular
    task:
      id: b5ac93ea-c625-4e44-862a-df43ebc242ea
      version: -1
      name: UnEscapeURL
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      input:
        simple: hxxps://www[.]demisto[.]com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 327f6b8e-e17a-4a6d-80e5-805f4cf37314
    type: regular
    task:
      id: 327f6b8e-e17a-4a6d-80e5-805f4cf37314
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: e57e6f75-6fa3-42e3-8ec3-a5bfa2c692ed
    type: regular
    task:
      id: e57e6f75-6fa3-42e3-8ec3-a5bfa2c692ed
      version: -1
      name: UnEscapeURLs an Array of urls
      description: |-
        Extract original URLs from Protected URLs from security tools like Proofpoint and and Microsoft ATP.
        Changes https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com_something.html -> https://example.com/something.html
        Changes na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fexample.com -> https://example.com
        Also, un-escape URLs that are escaped for safety with formats like hxxps://www[.]demisto[.]com
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
      - "19"
    scriptarguments:
      input:
        simple: https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FPhilipsBeLux&data=02|01||cb2462dc8640484baf7608d638d2a698|1a407a2d76754d178692b3ac285306e4|0|0|636758874714819880&sdata=rSVqfaVO2V23rdg6L7rly%2BbWdn4WmvUk1T5YQ8%2BACbk%3D&reserved=0%3E,https://urldefense.proofpoint.com/v2/url?u=http-3A__go.getpostman.com_y4wULsdG0h0DDMY0Dv00100&d=DwMFaQ&c=ywDJJevdGcjv4rm9P3FcNg&r=s5kA2oIAQRXsacJiBKmTORIWyRN39ZKhobje2GyRgNs&m=vN1dVSiZvEoM9oExtQqEptm9Dbvq9tnjACDZzrBLaWI&s=zroN7KQdBCPBOfhOmv5SP1DDzZKZ1y9I3x4STS5PbHA&e=,hxxps://www[.]demisto[.]com,https://google.com,www.spotify.com # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2415,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 0affdd1b-af17-432b-8811-a77fd52b1d81
    type: regular
    task:
      id: 0affdd1b-af17-432b-8811-a77fd52b1d81
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "2"
      substring:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 11e1f0e6-f719-4e0e-8da1-80a89d9aba76
    type: regular
    task:
      id: 11e1f0e6-f719-4e0e-8da1-80a89d9aba76
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
      substring:
        simple: https://www.facebook.com/PhilipsBeLux # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 34f5263d-9f9a-4889-8164-3d3d3ab0197b
    type: regular
    task:
      id: 34f5263d-9f9a-4889-8164-3d3d3ab0197b
      version: -1
      name: UnEscapeURL with capitalized 'HTTPS'
      description: |-
        Extract original URLs from Protected URLs from security tools like Proofpoint and and Microsoft ATP.
        Changes https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com_something.html -> https://example.com/something.html
        Changes na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fexample.com -> https://example.com
        Also, un-escape URLs that are escaped for safety with formats like hxxps://www[.]demisto[.]com
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      extend-context:
        simple: output=
      input:
        simple: HTTPS://autodesk.com/poststuff # disable-secrets-detection
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 6937cc6f-825d-457f-8fd4-315f74b6f721
    type: condition
    task:
      id: 6937cc6f-825d-457f-8fd4-315f74b6f721
      version: -1
      name: Verify that the output URL is correct
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    scriptarguments:
      left:
        complex:
          root: output
      right:
        simple: https://autodesk.com/poststuff # disable-secrets-detection
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 3390,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
