id: ExtraHop-Test
version: -1
name: ExtraHop-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2a774637-8d52-4c88-8417-340fc29c2748
    type: start
    task:
      id: 2a774637-8d52-4c88-8417-340fc29c2748
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 837b5c53-4fb7-40a7-82cc-0259bfb03db9
    type: regular
    task:
      id: 837b5c53-4fb7-40a7-82cc-0259bfb03db9
      version: -1
      name: extrahop-get-alerts
      description: Get alerts from Extra Hop
      script: ExtraHop|||extrahop-get-alerts
      type: regular
      iscommand: true
      brand: ExtraHop
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: cd474bbb-cea3-4957-818a-f47980ab915a
    type: regular
    task:
      id: cd474bbb-cea3-4957-818a-f47980ab915a
      version: -1
      name: extrahop-devices
      script: ExtraHop|||extrahop-devices
      type: regular
      iscommand: true
      brand: ExtraHop
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      active_from: {}
      active_until: {}
      limit: {}
      search_type:
        simple: any
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: dafeda6b-64be-4ec1-8ef7-7c27acc82995
    type: regular
    task:
      id: dafeda6b-64be-4ec1-8ef7-7c27acc82995
      version: -1
      name: extrahop-whitelist-retrieve
      script: ExtraHop|||extrahop-whitelist-retrieve
      type: regular
      iscommand: true
      brand: ExtraHop
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 635,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
