id: IntSights Mssp Test
version: -1
name: IntSights Mssp Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4de7dcd9-7e58-432e-8ef4-2d0c6335b348
    type: start
    task:
      id: 4de7dcd9-7e58-432e-8ef4-2d0c6335b348
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 229f401f-a723-4b35-8872-61557ffd9f9f
    type: regular
    task:
      id: 229f401f-a723-4b35-8872-61557ffd9f9f
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 467f5a0b-c960-45cd-8635-d668387c7046
    type: regular
    task:
      id: 467f5a0b-c960-45cd-8635-d668387c7046
      version: -1
      name: Test mssp feature
      script: '|||intsights-mssp-test'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 7aa2f202-ed7a-4819-8271-17d8b55c2e41
    type: condition
    task:
      id: 7aa2f202-ed7a-4819-8271-17d8b55c2e41
      version: -1
      name: Test mssp different sub accounts
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "4"
    scriptarguments:
      left:
        simple: IntSights.MsspAccounts.[0]._id
      right:
        simple: IntSights.MsspAccounts.[1]._id
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: cc834b16-193c-421e-8d50-b4ba8fc376f4
    type: title
    task:
      id: cc834b16-193c-421e-8d50-b4ba8fc376f4
      version: -1
      name: Good result
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
