id: 270e9681-9775-43ef-8eed-5735df6bd156
version: 34
name: ZipFile-Test
description: Test ZipFile and UnzipFile scripts
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 03783473-e075-4ca8-8de8-9dbad47fa8df
    type: start
    task:
      id: 03783473-e075-4ca8-8de8-9dbad47fa8df
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -200
        }
      }
    note: false
  "1":
    id: "1"
    taskid: e0abbdd7-6fff-4431-8aad-c291d5fd11fd
    type: regular
    task:
      id: e0abbdd7-6fff-4431-8aad-c291d5fd11fd
      version: -1
      name: http
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      body: {}
      filename:
        simple: test.zip
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/blob/master/TestData/TestImage.jpg.zip?raw=true
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 90
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 5c0ee0f9-599f-4a19-80bc-c0094f8f52c9
    type: regular
    task:
      id: 5c0ee0f9-599f-4a19-80bc-c0094f8f52c9
      version: -1
      name: UnzipFile
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      scriptName: UnzipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        simple: '{ENCRYPTED}Agrn7bHc9tA+Or7VMAcjoLRn0giBKLTnDkqtL8yrmoFHmUZorGAUgGAmB+z3trwEn9e5AMpYGLyWpE4slO7pHw=='
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
    note: false
  "4":
    id: "4"
    taskid: f0586d3e-9846-4d34-8949-83390e6d9899
    type: regular
    task:
      id: f0586d3e-9846-4d34-8949-83390e6d9899
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -70
        }
      }
    note: false
  "7":
    id: "7"
    taskid: 5ec42902-9d57-4034-8d26-b6dba40fe345
    type: condition
    task:
      id: 5ec42902-9d57-4034-8d26-b6dba40fe345
      version: -1
      name: VerifySuccessfulCycle
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: File.[2].Info
            iscontext: true
          right:
            value:
              simple: application/zip
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
    note: false
  "8":
    id: "8"
    taskid: 30c92aa8-4bfb-4795-828f-f76201ca4a30
    type: regular
    task:
      id: 30c92aa8-4bfb-4795-828f-f76201ca4a30
      version: -1
      name: ZipFile
      description: Zip a file and upload to war room
      scriptName: ZipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      entryID:
        simple: ${File.[1].EntryID}
      password: {}
      zipName: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 400
        }
      }
    note: false
  "9":
    id: "9"
    taskid: 19372156-70ae-46f9-86b1-6cfc4d0ce8f0
    type: regular
    task:
      id: 19372156-70ae-46f9-86b1-6cfc4d0ce8f0
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 900,
          "y": -70
        }
      }
    note: false
  "10":
    id: "10"
    taskid: 725fb93f-d942-4e05-8c6b-0a0cfd7ca263
    type: regular
    task:
      id: 725fb93f-d942-4e05-8c6b-0a0cfd7ca263
      version: -1
      name: http
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      body: {}
      filename:
        simple: test.7z
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/blob/master/TestData/TestImage.jpg.7z?raw=true
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 900,
          "y": 90
        }
      }
    note: false
  "11":
    id: "11"
    taskid: 015b0e9a-6312-4896-84a1-3146a2becd71
    type: regular
    task:
      id: 015b0e9a-6312-4896-84a1-3146a2becd71
      version: -1
      name: UnzipFile
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      scriptName: UnzipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        simple: '{ENCRYPTED}Agrn7bHc9tA+Or7VMAcjoLRn0giBKLTnDkqtL8yrmoFHmUZorGAUgGAmB+z3trwEn9e5AMpYGLyWpE4slO7pHw=='
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 900,
          "y": 240
        }
      }
    note: false
  "12":
    id: "12"
    taskid: 6774be3c-06f2-46da-8381-0234c524d434
    type: condition
    task:
      id: 6774be3c-06f2-46da-8381-0234c524d434
      version: -1
      name: VerifySuccessfulCycle
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: File.[1].Info
            iscontext: true
          right:
            value:
              simple: image/jpeg
    view: |-
      {
        "position": {
          "x": 900,
          "y": 570
        }
      }
    note: false
  "13":
    id: "13"
    taskid: 8cedc47f-3567-412e-8a94-ab88e5d9408d
    type: regular
    task:
      id: 8cedc47f-3567-412e-8a94-ab88e5d9408d
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": -70
        }
      }
    note: false
  "14":
    id: "14"
    taskid: e271f1cb-3e1d-418a-8145-88b8a551ba09
    type: regular
    task:
      id: e271f1cb-3e1d-418a-8145-88b8a551ba09
      version: -1
      name: http
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      body: {}
      filename:
        simple: test.tar
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/blob/master/TestData/TestImage.jpg.tar?raw=true
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 90
        }
      }
    note: false
  "15":
    id: "15"
    taskid: bb8fa513-4249-42ab-8f55-24534ae32766
    type: regular
    task:
      id: bb8fa513-4249-42ab-8f55-24534ae32766
      version: -1
      name: UnzipFile
      description: Unzip a file using fileName or entryID to specify a file. Files
        unzipped will be pushed to the war room and names will be pushed to the context.
      scriptName: UnzipFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
      fileName: {}
      lastZipFileInWarroom: {}
      password:
        simple: '{ENCRYPTED}Agrn7bHc9tA+Or7VMAcjoLRn0giBKLTnDkqtL8yrmoFHmUZorGAUgGAmB+z3trwEn9e5AMpYGLyWpE4slO7pHw=='
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 240
        }
      }
    note: false
  "16":
    id: "16"
    taskid: 00ce7d19-6e78-4ab4-8f0d-944a6aab9a3f
    type: condition
    task:
      id: 00ce7d19-6e78-4ab4-8f0d-944a6aab9a3f
      version: -1
      name: VerifySuccessfulCycle
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: File.[1].Info
            iscontext: true
          right:
            value:
              simple: image/jpeg
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 570
        }
      }
    note: false
  "17":
    id: "17"
    taskid: 4a0a616f-fbec-4f6a-8134-1386ecb7b0e5
    type: regular
    task:
      id: 4a0a616f-fbec-4f6a-8134-1386ecb7b0e5
      version: -1
      name: CloseInvestigation
      description: Close an investigation
      scriptName: CloseInvestigation
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      notes: {}
      reason: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 750
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1045,
        "width": 1270,
        "x": 450,
        "y": -200
      }
    }
  }
inputs: []
outputs: []
