id: sqs_test
version: -1
name: sqs_test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0e1cf1fc-e88d-4bc0-8070-eaf71c4bafc8
    type: start
    task:
      id: 0e1cf1fc-e88d-4bc0-8070-eaf71c4bafc8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -242
        }
      }
  "1":
    id: "1"
    taskid: fff04121-53e0-42c4-83e1-924478d62ca1
    type: regular
    task:
      id: fff04121-53e0-42c4-83e1-924478d62ca1
      version: -1
      name: sqs-list-queues
      description: Returns a list of your queues
      script: SQS|||sqs-list-queues
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      queueNamePrefix: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1497
        }
      }
  "2":
    id: "2"
    taskid: cb359925-88e0-434d-80fa-cf7be2f32b76
    type: regular
    task:
      id: cb359925-88e0-434d-80fa-cf7be2f32b76
      version: -1
      name: sqs-get-messages
      description: Gets up to 10 messages from the Queue
      script: SQS|||sqs-get-messages
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "9"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1027
        }
      }
  "3":
    id: "3"
    taskid: 57d10a13-29d6-483a-8fcf-ad3fb31b9c37
    type: regular
    task:
      id: 57d10a13-29d6-483a-8fcf-ad3fb31b9c37
      version: -1
      name: sqs-delete-messages
      description: Deletes up to 10 messages from the Queue
      script: SQS|||sqs-delete-messages
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      deleteAll:
        simple: "yes"
      maxMessages: {}
      receiptHandles: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1942
        }
      }
  "4":
    id: "4"
    taskid: e376cbad-7ee0-4716-8b0c-96e637a95355
    type: title
    task:
      id: e376cbad-7ee0-4716-8b0c-96e637a95355
      version: -1
      name: SQS test playbook
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -33
        }
      }
  "5":
    id: "5"
    taskid: 91637d5f-e709-4c5c-8d09-0dc548724e4f
    type: regular
    task:
      id: 91637d5f-e709-4c5c-8d09-0dc548724e4f
      version: -1
      name: sqs-send-message
      description: Sends a message to the queue
      script: SQS|||sqs-send-message
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      Body:
        simple: verwgb5
      Delay: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 524
        }
      }
  "6":
    id: "6"
    taskid: 2d67331d-261e-4149-8fa4-9272d9fe3c7a
    type: regular
    task:
      id: 2d67331d-261e-4149-8fa4-9272d9fe3c7a
      version: -1
      name: sqs-send-message
      description: Sends a message to the queue
      script: SQS|||sqs-send-message
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      Body:
        simple: r4klh234fn4k52 g3±!@#$@%&$^MUY
      Delay: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 375
        }
      }
  "7":
    id: "7"
    taskid: 67f1157a-28ad-4ec0-8cd9-1a1ae797f9a2
    type: regular
    task:
      id: 67f1157a-28ad-4ec0-8cd9-1a1ae797f9a2
      version: -1
      name: sqs-send-message
      description: Sends a message to the queue
      script: SQS|||sqs-send-message
      type: regular
      iscommand: true
      brand: SQS
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      Body:
        simple: gbtbeu6jn
      Delay: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 687
        }
      }
  "8":
    id: "8"
    taskid: 97cafbad-4dda-4632-8177-145f1c862bd9
    type: regular
    task:
      id: 97cafbad-4dda-4632-8177-145f1c862bd9
      version: -1
      name: Sleep for 11s
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      seconds:
        simple: "11"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 867
        }
      }
  "9":
    id: "9"
    taskid: 6569d639-6718-4154-8afd-548eb1d5dd77
    type: condition
    task:
      id: 6569d639-6718-4154-8afd-548eb1d5dd77
      version: -1
      name: Verify get messages
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "1"
    scriptarguments:
      left:
        simple: ${SQS.Messages.Body}
      right:
        simple: gbtbeu6jn
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1229
        }
      }
  "11":
    id: "11"
    taskid: 484d8aaa-ea6b-434c-86e7-a59cced200ca
    type: regular
    task:
      id: 484d8aaa-ea6b-434c-86e7-a59cced200ca
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 159
        }
      }
  "12":
    id: "12"
    taskid: 83119c2b-ff94-4d82-82ce-e6ee111d802a
    type: regular
    task:
      id: 83119c2b-ff94-4d82-82ce-e6ee111d802a
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      all:
        simple: "yes"
      key: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2123
        }
      }
  "13":
    id: "13"
    taskid: ce584fba-66d6-4b1d-846a-698fbbf5ae0b
    type: condition
    task:
      id: ce584fba-66d6-4b1d-846a-698fbbf5ae0b
      version: -1
      name: AreValuesEqual
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    scriptarguments:
      left:
        simple: ${SQS.QueueUrls}
      right:
        simple: https://us-east-2.queue.amazonaws.com/676921422616/playbook_test
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1738
        }
      }
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2460,
        "width": 380,
        "x": 450,
        "y": -242
      }
    }
  }
inputs: []
outputs: []