id: PhishLabsIOC TestPlaybook
version: -1
name: PhishLabsIOC TestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 99edd808-d233-4d28-8bba-72da92937f84
    type: start
    task:
      id: 99edd808-d233-4d28-8bba-72da92937f84
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: e686029b-188f-4350-816c-208977a8ea9e
    type: regular
    task:
      id: e686029b-188f-4350-816c-208977a8ea9e
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 072a4073-a3a2-4b11-88bb-983deea06fe9
    type: regular
    task:
      id: 072a4073-a3a2-4b11-88bb-983deea06fe9
      version: -1
      name: Global Feed - URL
      description: Gets the global IOC feed from PhishLabs
      script: PhishLabsIOC|||phishlabs-global-feed
      type: regular
      iscommand: true
      brand: PhishLabsIOC
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: URL
      limit:
        simple: "5"
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 718393b6-53d3-4e48-8aae-5e61f9531022
    type: condition
    task:
      id: 718393b6-53d3-4e48-8aae-5e61f9531022
      version: -1
      name: Verify URL
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: URL.Data
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabs.URL.Data
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 545be7d3-7bf5-4752-8ea8-ebcfb6bee553
    type: regular
    task:
      id: 545be7d3-7bf5-4752-8ea8-ebcfb6bee553
      version: -1
      name: Global Feed - Domain
      description: Gets the global IOC feed from PhishLabs
      script: PhishLabsIOC|||phishlabs-global-feed
      type: regular
      iscommand: true
      brand: PhishLabsIOC
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: Domain
      limit:
        simple: "5"
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: f390ee60-1028-4dba-884e-7ca5f5421572
    type: condition
    task:
      id: f390ee60-1028-4dba-884e-7ca5f5421572
      version: -1
      name: Verify Domain
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: Domain.Name
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabs.Domain.Name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: a4be7a79-72b2-451b-8dc0-d9e74e142661
    type: regular
    task:
      id: a4be7a79-72b2-451b-8dc0-d9e74e142661
      version: -1
      name: Global Feed - Attachment
      description: Gets the global IOC feed from PhishLabs
      script: PhishLabsIOC|||phishlabs-global-feed
      type: regular
      iscommand: true
      brand: PhishLabsIOC
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      false_positive: {}
      indicator_type:
        simple: Attachment
      limit:
        simple: "5"
      offset: {}
      remove_protocol: {}
      remove_query: {}
      since:
        simple: 365d
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: f07496b1-756d-4792-873d-26412185e5f1
    type: condition
    task:
      id: f07496b1-756d-4792-873d-26412185e5f1
      version: -1
      name: Verify File
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: File.MD5
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabs.File.MD5
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: de22de97-a0b0-4481-88dd-7ff2bfe98d85
    type: regular
    task:
      id: de22de97-a0b0-4481-88dd-7ff2bfe98d85
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 25bdbf84-1c7e-4193-8dbd-003e85ee10f6
    type: regular
    task:
      id: 25bdbf84-1c7e-4193-8dbd-003e85ee10f6
      version: -1
      name: Get incident indicators
      description: Gets indicators from a speicifed PhishLabs incident.
      script: PhishLabsIOC|||phishlabs-get-incident-indicators
      type: regular
      iscommand: true
      brand: PhishLabsIOC
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      id:
        simple: INC0015516
      indicator_type: {}
      indicators_classification: {}
      limit: {}
      offset: {}
      since:
        simple: 365d
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 8b84b28b-3c8e-4067-8c31-cfd112f303e4
    type: condition
    task:
      id: 8b84b28b-3c8e-4067-8c31-cfd112f303e4
      version: -1
      name: Verify URL
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: URL.Data
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabs.URL.Data
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: c42454cd-fe68-49d2-8114-1f5abbc536c0
    type: condition
    task:
      id: c42454cd-fe68-49d2-8114-1f5abbc536c0
      version: -1
      name: Verify Email
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "12"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: Email
                accessor: Body
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabs.Email.Body
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 68a2b5cc-2ef8-4787-894c-604291cd9806
    type: regular
    task:
      id: 68a2b5cc-2ef8-4787-894c-604291cd9806
      version: -1
      name: Populate indicators
      description: Populate indicators by the PhishLabs IOC  global feed.
      scriptName: PhishLabsPopulateIndicators
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      delete_false_positive: {}
      indicator_type: {}
      limit:
        simple: "5"
      since:
        simple: 365d
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: edb614dd-925e-4234-8aa8-61ee4ae8de87
    type: regular
    task:
      id: edb614dd-925e-4234-8aa8-61ee4ae8de87
      version: -1
      name: Find indicators
      description: Finds all indicators with given value.
      script: Builtin|||findIndicators
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      extend-context:
        simple: Source=source
      fromdate: {}
      query:
        simple: source:PhishLabs
      size: {}
      todate: {}
      value: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 9fcfc739-a4b2-4788-826b-ba249e554ad8
    type: condition
    task:
      id: 9fcfc739-a4b2-4788-826b-ba249e554ad8
      version: -1
      name: Verify PhishLabs indicators
      description: Verify given entry contains a string
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: ${Source}
            iscontext: true
          right:
            value:
              simple: PhishLabs
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2645
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: f5a88daa-96eb-4087-86d6-389b2cb814ce
    type: regular
    task:
      id: f5a88daa-96eb-4087-86d6-389b2cb814ce
      version: -1
      name: Test fetch
      description: Execute FetchIncident for a given instance
      scriptName: FetchFromInstance
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      add_to_context: {}
      brand_name:
        simple: PhishLabsIOC
      error_msg_in_incident: {}
      expect_data: {}
      instance_name: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 0acc247a-05ee-4669-8c5e-29826e03cb61
    type: title
    task:
      id: 0acc247a-05ee-4669-8c5e-29826e03cb61
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2995
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 523f005a-85e9-4438-8fe6-c2a08028f154
    type: regular
    task:
      id: 523f005a-85e9-4438-8fe6-c2a08028f154
      version: -1
      name: Sleep
      description: Sleep for X seconds
      scriptName: Sleep
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      seconds:
        simple: "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3010,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
