id: RecordedFutureFeed - Test
version: -1
contentitemfields:
  propagationLabels:
  - all
name: RecordedFutureFeed - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 4a47841a-9067-4c0e-814b-44439d608f3b
    type: start
    task:
      id: 4a47841a-9067-4c0e-814b-44439d608f3b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: 9db2b09c-4822-4cb0-89ea-09c06ea5d438
    type: regular
    task:
      id: 9db2b09c-4822-4cb0-89ea-09c06ea5d438
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "3"
      - "5"
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: 12927a9d-0e7b-441e-8114-3e68214a86e0
    type: regular
    task:
      id: 12927a9d-0e7b-441e-8114-3e68214a86e0
      version: -1
      name: get-indicators-ip
      description: Get indicators from the feed
      script: FeedRecordedFuture|||get-indicators
      type: regular
      iscommand: true
      brand: FeedRecordedFuture
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      indicator_type:
        simple: ip
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: fe2259b6-c9fc-40a3-8ca1-804bdb800cf0
    type: regular
    task:
      id: fe2259b6-c9fc-40a3-8ca1-804bdb800cf0
      version: -1
      name: get-indicators-domain
      description: Get indicators from the feed
      script: FeedRecordedFuture|||get-indicators
      type: regular
      iscommand: true
      brand: FeedRecordedFuture
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      indicator_type:
        simple: domain
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: e8136895-3a41-4306-8fb9-8b43244269d6
    type: regular
    task:
      id: e8136895-3a41-4306-8fb9-8b43244269d6
      version: -1
      name: get-indicators-hash
      description: Get indicators from the feed
      script: FeedRecordedFuture|||get-indicators
      type: regular
      iscommand: true
      brand: FeedRecordedFuture
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      indicator_type:
        simple: hash
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "5":
    id: "5"
    taskid: 69433423-3ad3-47cd-8066-3003400d3395
    type: regular
    task:
      id: 69433423-3ad3-47cd-8066-3003400d3395
      version: -1
      name: get-indicators-url
      description: Get indicators from the feed
      script: FeedRecordedFuture|||get-indicators
      type: regular
      iscommand: true
      brand: FeedRecordedFuture
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      indicator_type:
        simple: url
      limit:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "6":
    id: "6"
    taskid: 4b48e968-9ae1-402e-8356-bcc6113814cf
    type: condition
    task:
      id: 4b48e968-9ae1-402e-8356-bcc6113814cf
      version: -1
      name: verify get indicators-ip
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Type
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "7":
    id: "7"
    taskid: 0d219d5b-730d-4d6b-8a9d-914fd558a493
    type: condition
    task:
      id: 0d219d5b-730d-4d6b-8a9d-914fd558a493
      version: -1
      name: verify get indicators-domain
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Type
            iscontext: true
          right:
            value:
              simple: Domain
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "8":
    id: "8"
    taskid: 8150b4a2-30db-49f8-8a7e-5c1e23f70254
    type: condition
    task:
      id: 8150b4a2-30db-49f8-8a7e-5c1e23f70254
      version: -1
      name: verify get indicators-url
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Type
            iscontext: true
          right:
            value:
              simple: URL
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "9":
    id: "9"
    taskid: 160cb36b-c153-4b83-86bc-460e42ab73dd
    type: condition
    task:
      id: 160cb36b-c153-4b83-86bc-460e42ab73dd
      version: -1
      name: verify get indicators-hash
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Type
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.Indicator.Value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "10":
    id: "10"
    taskid: c009081c-1222-4298-8072-f0f7e3450f9f
    type: regular
    task:
      id: c009081c-1222-4298-8072-f0f7e3450f9f
      version: -1
      name: get-indicators error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Get-indicator failed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 60,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "11":
    id: "11"
    taskid: 1c58cfb3-b6c3-4a4c-8788-29bd92c68506
    type: regular
    task:
      id: 1c58cfb3-b6c3-4a4c-8788-29bd92c68506
      version: -1
      name: get-risk-rules
      description: Get a list of the risk rules available for an indicator
      script: FeedRecordedFuture|||get-risk-rules
      type: regular
      iscommand: true
      brand: FeedRecordedFuture
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      indicator_type:
        simple: ip
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "12":
    id: "12"
    taskid: 1c6ce6ec-eb82-46df-861f-399d0e5de6e3
    type: condition
    task:
      id: 1c6ce6ec-eb82-46df-861f-399d0e5de6e3
      version: -1
      name: verify risk rules
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "13"
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.RiskRule.Name
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.RiskRule.Description
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: RecordedFutureFeed.RiskRule.Criticality
            iscontext: true
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "13":
    id: "13"
    taskid: 1f43061d-d68d-4bb1-8fce-a56dfa1a20d9
    type: regular
    task:
      id: 1f43061d-d68d-4bb1-8fce-a56dfa1a20d9
      version: -1
      name: get-risk-rules error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: get-risk-rules command failed
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "14":
    id: "14"
    taskid: bbe0d801-9cc7-43ae-8dab-f8ee2c00e9e6
    type: title
    task:
      id: bbe0d801-9cc7-43ae-8dab-f8ee2c00e9e6
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1565,
          "y": 1085
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 1895,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
