id: EC2-Test-Read
version: 1
name: EC2-Test-Read
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 59ed3450-aaca-4f7b-89bb-8983600e7d3b
    type: start
    task:
      id: 59ed3450-aaca-4f7b-89bb-8983600e7d3b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 61e3bd34-5607-435d-88ac-c3bfe1fb3096
    type: regular
    task:
      id: 61e3bd34-5607-435d-88ac-c3bfe1fb3096
      version: -1
      name: aws-ec2-describe-instances
      description: Describes one or more of your instances.
      script: AWS - EC2 (test fail) |||aws-ec2-describe-instances
      type: regular
      iscommand: true
      brand: AWS - EC2
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      filters: {}
      instanceIds: {}
      region: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 744ec4af-4b3f-42c7-8f5d-db077276c9cd
    type: regular
    task:
      id: 744ec4af-4b3f-42c7-8f5d-db077276c9cd
      version: -1
      name: aws-ec2-describe-regions
      description: Describes one or more regions that are currently available to you.
      script: AWS - EC2 |||aws-ec2-describe-regions
      type: regular
      iscommand: true
      brand: AWS - EC2
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      region: {}
      regionNames: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 0ec50890-9844-4bfb-8578-6e46b751ee53
    type: regular
    task:
      id: 0ec50890-9844-4bfb-8578-6e46b751ee53
      version: -1
      name: aws-ec2-describe-snapshots
      description: Describes one or more of the EBS snapshots available to you.
      script: AWS - EC2|||aws-ec2-describe-snapshots
      type: regular
      iscommand: true
      brand: AWS - EC2
    scriptarguments:
      filters: {}
      ownerIds: {}
      region: {}
      restorableByUserIds: {}
      roleArn: {}
      roleSessionDuration: {}
      roleSessionName: {}
      snapshotIds:
        simple: snap-0776ecb88e4bd1431
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 590
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 635,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
