id: playbook-PcapHTTPExtractor-test
version: -1
name: playbook-PcapHTTPExtractor-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 0ed5ccfc-ad1a-4369-857b-54ed961c5621
    type: start
    task:
      id: 0ed5ccfc-ad1a-4369-857b-54ed961c5621
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: 8f7e9ba0-b987-44ab-8375-f8d073518530
    type: regular
    task:
      id: 8f7e9ba0-b987-44ab-8375-f8d073518530
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 1ae67f3e-7fa4-47df-8693-cb43534ce3ba
    type: regular
    task:
      id: 1ae67f3e-7fa4-47df-8693-cb43534ce3ba
      version: -1
      name: Get Remote File
      scriptName: http
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile:
        simple: "yes"
      unsecure: {}
      url:
        simple: https://github.com/demisto/content/raw/master/TestData/TestPcapPost.pcap
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 15f54d71-8dba-4e77-8b88-9cafa91bf680
    type: regular
    task:
      id: 15f54d71-8dba-4e77-8b88-9cafa91bf680
      version: -1
      name: PcapHTTPExtractor
      description: Allows to parse and extract http flows (requests & responses) from
        a pcap/pcapng file.
      scriptName: PcapHTTPExtractor
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      allowedContentTypes: {}
      entryID:
        simple: ${File.EntryID}
      limit: {}
      limitData: {}
      pcapFileName: {}
      start: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: c48ac5c1-0a8e-4e09-8bbe-0918e22510cc
    type: condition
    task:
      id: c48ac5c1-0a8e-4e09-8bbe-0918e22510cc
      version: -1
      name: IsResultContextCorrect
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: PcapHTTPFlows
                accessor: '[1].Response.HttpDate'
                transformers:
                - operator: trim
            iscontext: true
          right:
            value:
              simple: 2019-01-14T11:20:42
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 18195139-4241-4a55-86e5-d2e6c07711e1
    type: regular
    task:
      id: 18195139-4241-4a55-86e5-d2e6c07711e1
      version: -1
      name: Completed
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -140,
          "y": 920
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: d5c6840e-1ab0-48ee-8ed2-5b770d23e2ed
    type: regular
    task:
      id: d5c6840e-1ab0-48ee-8ed2-5b770d23e2ed
      version: -1
      name: Error
      type: regular
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 290,
          "y": 920
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 965,
        "width": 810,
        "x": -140,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
