id: QRadar Indicator Hunting Test
version: -1
name: QRadar Indicator Hunting Test
fromversion: 4.5.0
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: e85881b9-a5a8-439b-8b1e-fc232c41d6fa
    type: start
    task:
      id: e85881b9-a5a8-439b-8b1e-fc232c41d6fa
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: c1815fd6-bb3b-493f-8271-1fcbcd5bfae8
    type: regular
    task:
      id: c1815fd6-bb3b-493f-8271-1fcbcd5bfae8
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '3':
    id: '3'
    taskid: d0768b12-0a74-46cd-8aa3-4cdbae748bcd
    type: playbook
    task:
      id: d0768b12-0a74-46cd-8aa3-4cdbae748bcd
      version: -1
      name: QRadar Indicator Hunting
      description: ''
      playbookName: QRadar Indicator Hunting
      type: playbook
      iscommand: false
      brand: ''
    scriptarguments:
      IPAddress:
        simple: 66.196.219.2,54.238.142.98
      MD5:
        simple: avavavavavavavavavavav,bcbcbcbcbcbcbcb
      QradarIPfield:
        simple: sourceip,destinationip
      QradarMD5Field: {}
      QradarSHA1Field:
        simple: file hash
      QradarSHA256Field:
        simple: file hash,root hash
      SHA1:
        simple: avavavavavavavavavavav,bcbcbcbcbcbcbcb
      SHA256:
        simple: avavavavavavavavavavav,bcbcbcbcbcbcbcb
      SelectFields:
        simple: '*'
      TimeFrame:
        simple: LAST 1 DAYS
      URLDomain:
        simple: google,walla.com
      URLDomainField:
        simple: url
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
