id: Google-KMS-test
version: -1
name: Google-KMS-test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6b37caf1-7f7a-4a96-88bf-64ac48c48b1b
    type: start
    task:
      id: 6b37caf1-7f7a-4a96-88bf-64ac48c48b1b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 1ecdbcd9-ac17-4049-890b-c00bbd37705e
    type: regular
    task:
      id: 1ecdbcd9-ac17-4049-890b-c00bbd37705e
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "35"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: d87a7285-63e9-493d-83df-f356921b99f0
    type: condition
    task:
      id: d87a7285-63e9-493d-83df-f356921b99f0
      version: -1
      name: Check CryptoKey
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: GoogleKMS.CryptoKey.Name
            iscontext: true
          right:
            value:
              simple: projects/kms-integration/locations/global/keyRings/TestKeyRing/cryptoKeys/TestCryptoKey
    view: |-
      {
        "position": {
          "x": 450,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: c6d8672d-b031-4c33-83f4-5b27ccbd201f
    type: regular
    task:
      id: c6d8672d-b031-4c33-83f4-5b27ccbd201f
      version: -1
      name: google-kms-destroy-key
      description: Destroy the primary CryptoKeyVersion of a given CryptoKey
      script: '|||google-kms-destroy-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      crypto_key_version: {}
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: bd123998-e946-4603-8c62-ff454277fc61
    type: regular
    task:
      id: bd123998-e946-4603-8c62-ff454277fc61
      version: -1
      name: google-kms-get-key
      description: Returns metadata for a given CryptoKey, as well as its primary
        CryptoKeyVersion.
      script: Google Key Management Service|||google-kms-get-key
      type: regular
      iscommand: true
      brand: Google Key Management Service
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 920
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: 76fecd58-a27e-47ec-8fc2-e58d5ae913fe
    type: condition
    task:
      id: 76fecd58-a27e-47ec-8fc2-e58d5ae913fe
      version: -1
      name: Check key destruction
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: GoogleKMS
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: GoogleKMS.CryptoKey.Name
                      iscontext: true
                    right:
                      value:
                        simple: new_name1
                accessor: CryptoKey.PrimaryCryptoKeyVersion.State
            iscontext: true
          right:
            value:
              simple: DESTROY_SCHEDULED
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: af4c0a9d-36e3-4416-8e68-1ae96a66fad6
    type: regular
    task:
      id: af4c0a9d-36e3-4416-8e68-1ae96a66fad6
      version: -1
      name: google-kms-restore-key
      description: Restore the primary CryptoKeyVersion of a given CryptoKey
      script: '|||google-kms-restore-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: e560389d-70ff-4ab5-8b83-d5cd99263663
    type: regular
    task:
      id: e560389d-70ff-4ab5-8b83-d5cd99263663
      version: -1
      name: google-kms-get-key
      description: Returns metadata for a given CryptoKey, as well as its primary
        CryptoKeyVersion.
      script: Google Key Management Service|||google-kms-get-key
      type: regular
      iscommand: true
      brand: Google Key Management Service
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: b9351f96-03f2-4a24-87a1-f6469337f198
    type: condition
    task:
      id: b9351f96-03f2-4a24-87a1-f6469337f198
      version: -1
      name: Check key restoration
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: GoogleKMS
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: GoogleKMS.CryptoKey.Name
                      iscontext: true
                    right:
                      value:
                        simple: new_name1
                accessor: CryptoKey.PrimaryCryptoKeyVersion.State
            iscontext: true
          right:
            value:
              simple: DISABLED
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: 298b7346-67b3-44e5-889b-5d18816c4f65
    type: regular
    task:
      id: 298b7346-67b3-44e5-889b-5d18816c4f65
      version: -1
      name: google-kms-enable-key
      description: Enable the primary CryptoKeyVersion of a given CryptoKey
      script: '|||google-kms-enable-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1870
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: bef60676-cfa2-4434-8ac2-d68a23fb9451
    type: regular
    task:
      id: bef60676-cfa2-4434-8ac2-d68a23fb9451
      version: -1
      name: google-kms-get-key
      description: Returns metadata for a given CryptoKey, as well as its primary
        CryptoKeyVersion.
      script: Google Key Management Service|||google-kms-get-key
      type: regular
      iscommand: true
      brand: Google Key Management Service
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: b86051ba-c045-4045-86db-f1ea656cd4ea
    type: condition
    task:
      id: b86051ba-c045-4045-86db-f1ea656cd4ea
      version: -1
      name: Check key enabled
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "17"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: GoogleKMS
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: GoogleKMS.CryptoKey.Name
                      iscontext: true
                    right:
                      value:
                        simple: new_name1
                accessor: CryptoKey.PrimaryCryptoKeyVersion.State
            iscontext: true
          right:
            value:
              simple: ENABLED
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: bbc5a954-2fdc-4f11-8985-4264c2f3c656
    type: regular
    task:
      id: bbc5a954-2fdc-4f11-8985-4264c2f3c656
      version: -1
      name: google-kms-disable-key
      description: Disable the primary CryptoKeyVersion of a given CryptoKey
      script: '|||google-kms-disable-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 6041b3e5-bd1a-46b5-8d37-7c607ed11a7b
    type: regular
    task:
      id: 6041b3e5-bd1a-46b5-8d37-7c607ed11a7b
      version: -1
      name: google-kms-get-key
      description: Returns metadata for a given CryptoKey, as well as its primary
        CryptoKeyVersion.
      script: Google Key Management Service|||google-kms-get-key
      type: regular
      iscommand: true
      brand: Google Key Management Service
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: df115a3f-2c46-4a7e-82e7-2a9563ae5c01
    type: condition
    task:
      id: df115a3f-2c46-4a7e-82e7-2a9563ae5c01
      version: -1
      name: Check key disabled
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "20"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: GoogleKMS
                filters:
                - - operator: containsString
                    left:
                      value:
                        simple: GoogleKMS.CryptoKey.Name
                      iscontext: true
                    right:
                      value:
                        simple: new_name1
                accessor: CryptoKey.PrimaryCryptoKeyVersion.State
            iscontext: true
          right:
            value:
              simple: DISABLED
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 80d82375-0bf3-46e3-8c9e-e692e469baea
    type: regular
    task:
      id: 80d82375-0bf3-46e3-8c9e-e692e469baea
      version: -1
      name: google-kms-enable-key
      description: Enable the primary CryptoKeyVersion of a given CryptoKey
      script: '|||google-kms-enable-key'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "34"
    scriptarguments:
      crypto_key_id:
        simple: new_name1
      key_ring_id: {}
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 2950
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "34":
    id: "34"
    taskid: 569ac20f-fac0-4290-8167-dbf37363904e
    type: title
    task:
      id: 569ac20f-fac0-4290-8167-dbf37363904e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 3140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "35":
    id: "35"
    taskid: 5e8a2592-bc0c-451c-879c-00aafe1f21fb
    type: regular
    task:
      id: 5e8a2592-bc0c-451c-879c-00aafe1f21fb
      version: -1
      name: google-kms-list-keys
      description: Lists all keys in key ring
      script: Google Key Management Service|||google-kms-list-keys
      type: regular
      iscommand: true
      brand: Google Key Management Service
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      key_ring_id: {}
      key_state:
        simple: ENABLED
      location_id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 365
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 3155,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
