id: Splunk Indicator Hunting Test
version: -1
fromversion: 5.0.0
name: Splunk Indicator Hunting Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: fbdee7b8-76eb-4c1b-8a52-34227516bc62
    type: start
    task:
      id: fbdee7b8-76eb-4c1b-8a52-34227516bc62
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '2'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: 6f31f267-b262-45c1-841f-9cf722326750
    type: playbook
    task:
      id: 6f31f267-b262-45c1-841f-9cf722326750
      version: -1
      name: Splunk Indicator Hunting
      description: ''
      playbookName: Splunk Indicator Hunting
      type: playbook
      iscommand: false
      brand: ''
    scriptarguments:
      IPAddress:
        simple: 1.1.1.1
      IndexName:
        simple: '*'
      InternalRange: {}
      InvestigationHostFields:
        simple: dest_nt_host
      InvestigationIPFields:
        simple: dest_ip,src_ip,src,dst
      InvestigationUserFields:
        simple: user_identity
      MD5:
        simple: xxxxxx8920ba0ddebaf5ea68ff97a93c
      SHA1:
        simple: xxxxxx8920ba0ddebaf5ea68ff97a93c,xxxxxx8920ba0ddebaf5ea234987592834759834275
      SHA256:
        simple: xxxxxx8920ba0ddebaf5ea68ff97a93c
      SelectFields: {}
      SplunkIPField:
        simple: ip
      SplunkMD5Field:
        simple: Caller_MD5,file_hash
      SplunkSHA1Field: {}
      SplunkSHA256Field:
        simple: file_hash
      SplunkURLDomainField: {}
      URLDomain:
        simple: goo,wall
      earliest_time:
        simple: -1d
      event_limit: {}
      latest_time: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: c4ed11c5-ff85-4e72-80db-2f85581a67f6
    type: regular
    task:
      id: c4ed11c5-ff85-4e72-80db-2f85581a67f6
      version: -1
      name: Delect Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 405,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []