id: Alexa Test Playbook
version: -1
rolename: []
name: Alexa Test Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 808bd5d8-2546-4c71-8cd6-ac8a3cda848b
    type: start
    task:
      id: 808bd5d8-2546-4c71-8cd6-ac8a3cda848b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
  "1":
    id: "1"
    taskid: d87d7da9-eee3-46b4-889a-dc513098b669
    type: regular
    task:
      id: d87d7da9-eee3-46b4-889a-dc513098b669
      version: -1
      name: awis-info
      description: Provides an Alexa ranking of the URL in question.
      script: Alexa Rank Indicator|||domain
      type: regular
      iscommand: true
      brand: Alexa Rank Indicator
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      domain:
        simple: google.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
  "2":
    id: "2"
    taskid: 53d60cd8-a705-4262-82b9-b821d8ae3526
    type: regular
    task:
      id: 53d60cd8-a705-4262-82b9-b821d8ae3526
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
  "3":
    id: "3"
    taskid: 2c6978d3-5285-49dc-84cf-352d38c93d0a
    type: condition
    task:
      id: 2c6978d3-5285-49dc-84cf-352d38c93d0a
      version: -1
      name: Check Trusted Site
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${DBotScore.Score}
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 450,
          "y": 510
        }
      }
    note: false
    timertriggers: []
  "4":
    id: "4"
    taskid: 9a28e817-5bec-4651-8117-46a42fd2e8b4
    type: regular
    task:
      id: 9a28e817-5bec-4651-8117-46a42fd2e8b4
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 180
        }
      }
    note: false
    timertriggers: []
  "5":
    id: "5"
    taskid: 3d0cefb3-fded-466f-8e62-506488bc1815
    type: regular
    task:
      id: 3d0cefb3-fded-466f-8e62-506488bc1815
      version: -1
      name: awis-info
      description: Provides an Alexa ranking of the URL in question.
      script: Alexa Rank Indicator|||domain
      type: regular
      iscommand: true
      brand: Alexa Rank Indicator
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      domain:
        simple: altcom.com.pl
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 350
        }
      }
    note: false
    timertriggers: []
  "6":
    id: "6"
    taskid: 27211a2e-c2c9-4a6f-89d4-ddf38084bfa9
    type: condition
    task:
      id: 27211a2e-c2c9-4a6f-89d4-ddf38084bfa9
      version: -1
      name: Check Low Ranking Site
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${DBotScore.Score}
            iscontext: true
          right:
            value:
              simple: "2"
    view: |-
      {
        "position": {
          "x": 890,
          "y": 510
        }
      }
    note: false
    timertriggers: []
  "7":
    id: "7"
    taskid: 1df3dbf5-36bb-4b4e-841f-6ff2934622d2
    type: regular
    task:
      id: 1df3dbf5-36bb-4b4e-841f-6ff2934622d2
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 180
        }
      }
    note: false
    timertriggers: []
  "8":
    id: "8"
    taskid: d2a068c0-3f76-4429-8e4a-e9485043ae58
    type: regular
    task:
      id: d2a068c0-3f76-4429-8e4a-e9485043ae58
      version: -1
      name: awis-info
      description: Provides an Alexa ranking of the URL in question.
      script: Alexa Rank Indicator|||domain
      type: regular
      iscommand: true
      brand: Alexa Rank Indicator
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      domain:
        simple: shlepme.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 350
        }
      }
    note: false
    timertriggers: []
  "9":
    id: "9"
    taskid: 5e717787-cf33-4752-8c78-822802074f09
    type: condition
    task:
      id: 5e717787-cf33-4752-8c78-822802074f09
      version: -1
      name: Check Unlisted Site
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${DBotScore.Score}
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 1330,
          "y": 510
        }
      }
    note: false
    timertriggers: []
  "10":
    id: "10"
    taskid: d3bc6702-551a-4991-8d27-2a0eb3bd2b1a
    type: regular
    task:
      id: d3bc6702-551a-4991-8d27-2a0eb3bd2b1a
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 890,
          "y": 700
        }
      }
    note: false
    timertriggers: []
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 1260,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
