commonfields:
  id: RaiseError
  version: -1
name: RaiseError
script: |-
  demisto.results({
      "Type" : entryTypes["error"],
      "ContentsFormat" : formats["text"],
      "Contents" : demisto.args()["error"]
  })
type: python
tags: []
comment: raise error
enabled: true
args:
- name: error
  required: true
  description: error to raise
scripttarget: 0
runonce: false
