version: 2
jobs:
  build:
    docker:
      - image: devdemisto/content-build:1.0.0.159 # disable-secrets-detection
    resource_class: medium+
    environment:
      CONTENT_VERSION: "19.3.1"
      GIT_SHA1: "6c42492a4b4c92e56e5e73412698c7284b555a84" # guardrails-disable-line disable-secrets-detection
    steps:
      - checkout
      - run:
          name: Prepare Environment
          command: |
              echo 'export CIRCLE_ARTIFACTS="/home/circleci/project/artifacts"' >> $BASH_ENV
              echo 'export PATH="/home/circleci/.local/bin:${PATH}"' >> $BASH_ENV
              echo 'export PYTHONPATH="/home/circleci/project:${PYTHONPATH}"' >> $BASH_ENV
              source $BASH_ENV
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              chmod +x ./Tests/scripts/*
              chmod +x ./Tests/lastest_server_build_scripts/*
              sudo pip install mock
      - add_ssh_keys:
          fingerprints:
              - "02:df:a5:6a:53:9a:f5:5d:bd:a6:fc:b2:db:9b:c9:47" # disable-secrets-detection
              - "f5:25:6a:e5:ac:4b:84:fb:60:54:14:82:f1:e9:6c:f9" # disable-secrets-detection
      - run:
          name: Infrastucture testing
          command: |
            pytest ./Tests/scripts/hook_validations/tests/ -v
            pytest ./Tests/scripts/infrastructure_tests/ -v
      - run:
          name: Build Content Descriptor
          command: ./setContentDescriptor.sh $CIRCLE_BUILD_NUM $GIT_SHA1 $CONTENT_VERSION
      - run:
          name: Common Server Documentation
          command: ./Documentation/commonServerDocs.sh
      - run:
          name: Create Content Artifacts
          command: python content_creator.py $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: artifacts
          destination: artifacts