version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11
    environment:
      CIRCLE_ARTIFACTS: "~/artifacts"
      CONTENT_VERSION: "18.5.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              sudo apt-get install -y python-dev libxml2-dev libxslt1-dev zlib1g-dev python-setuptools
              sudo easy_install pip
              sudo pip install pykwalify
              sudo npm install npm -g
              sudo pip install git+https://github.com/demisto/demisto-py.git@test-content
              sudo pip install pykwalify
              sudo npm install -g jsdoc-to-markdown
              sudo pip install git+https://github.com/rahulrrixe/parinx.git@master
      - run:
          name: Validate Files and Yaml
          command: |
              ./Tests/scripts/validate_files_structure.sh
              chmod +x ./Tests/yamlvalidator
              ./Tests/yamlvalidator
      - run:
          name: Build Content Descriptor
          command: ./setContentDescriptor.sh $CIRCLE_BUILD_NUM 1aeecc41f4640cfca92618bbefd44698f61b9c88 $CONTENT_VERSION
      - run:
          name: Common Server Documentation
          command: ./Docs/commonServerDocs.sh
      - run:
          name: Server Documentation
          command: python content_creator.py $CIRCLE_ARTIFACTS
      - run:
          name: GET DETAILS
          command: |
              pwd
              ls -l
              ls -l $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: artifacts
      - run:
          name: Setup Instance
          command: |
              ./Tests/scripts/server_get_artifact.sh
              ./Tests/scripts/create_instance.sh
              ./Tests/scripts/download_demisto_conf.sh
              ./Tests/scripts/run_installer_on_instance.sh
              ./Tests/scripts/wait_until_server_ready.sh
      - run:
          name: Run Tests
          command: ./Tests/scripts/run_tests.sh
      - run:
          name: Destory Instances
          command: ./Tests/scripts/destroy_instances.sh