id: CVE Search v2 - Test
version: -1
name: CVE Search v2 - Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 46fc3932-c960-4b07-8b8c-f4886f8c69fc
    type: start
    task:
      id: 46fc3932-c960-4b07-8b8c-f4886f8c69fc
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - '14'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '1':
    id: '1'
    taskid: 2d7de6a9-7d6f-4707-8927-c226e6b743ba
    type: regular
    task:
      id: 2d7de6a9-7d6f-4707-8927-c226e6b743ba
      version: -1
      name: Populate Error
      description: commands.local.cmd.get.entry
      script: Builtin|||getEntry
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      extend-context:
        simple: PreviousTaskOutput=
      id:
        simple: ${lastCompletedTaskEntries}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '3':
    id: '3'
    taskid: d854070c-ecc9-441d-82cd-cd3903557af2
    type: condition
    task:
      id: d854070c-ecc9-441d-82cd-cd3903557af2
      version: -1
      name: Validate Error type
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - '13'
      "yes":
      - '12'
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: endWith
          left:
            value:
              simple: PreviousTaskOutput
            iscontext: true
          right:
            value:
              simple: (read timeout=10)
    view: |-
      {
        "position": {
          "x": 60,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '4':
    id: '4'
    taskid: c7eba38c-af87-4cd4-8376-bd31d82504c9
    type: regular
    task:
      id: c7eba38c-af87-4cd4-8376-bd31d82504c9
      version: -1
      name: Populate Error
      description: commands.local.cmd.get.entry
      script: Builtin|||getEntry
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      extend-context:
        simple: PreviousTaskOutput=
      id:
        simple: ${lastCompletedTaskEntries}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '5':
    id: '5'
    taskid: 572a4a3f-303a-40fd-8379-8e0a59cbd2d5
    type: condition
    task:
      id: 572a4a3f-303a-40fd-8379-8e0a59cbd2d5
      version: -1
      name: Check if cve-latest return 30 entries
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - '3'
      "yes":
      - '12'
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: CVE
                accessor: ID
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "30"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '6':
    id: '6'
    taskid: 4fa90167-86a5-4a52-865a-abfdf47b8c95
    type: regular
    task:
      id: 4fa90167-86a5-4a52-865a-abfdf47b8c95
      version: -1
      name: cve-latest
      description: Retruns the latest updated CVEs.
      script: CVE Search v2|||cve-latest
      type: regular
      iscommand: true
      brand: CVE Search v2
    nexttasks:
      '#none#':
      - '1'
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '16':
    id: '16'
    taskid: 9fede8a9-e6a4-47d7-8050-12ef3b03a711
    type: regular
    task:
      id: 9fede8a9-e6a4-47d7-8050-12ef3b03a711
      version: -1
      name: Check cve
      description: Returns CVE information by CVE ID.
      script: CVE Search v2|||cve
      type: regular
      iscommand: true
      brand: CVE Search v2
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      cve_id:
        simple: CVE-2015-6541
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '8':
    id: '8'
    taskid: 62518c1d-0995-437c-8124-a3ef7312ac07
    type: regular
    task:
      id: 62518c1d-0995-437c-8124-a3ef7312ac07
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '9':
    id: '9'
    taskid: 9b05bca1-e464-4fd2-80c5-05abd71299ac
    type: title
    task:
      id: 9b05bca1-e464-4fd2-80c5-05abd71299ac
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '10':
    id: '10'
    taskid: 5c1d1f54-2bf0-4fa5-8d42-6f3973a6f14f
    type: regular
    task:
      id: 5c1d1f54-2bf0-4fa5-8d42-6f3973a6f14f
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: cve-latest did not return 30 last entires
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '11':
    id: '11'
    taskid: c6602c80-95e9-42e3-89b2-ebca91252734
    type: condition
    task:
      id: c6602c80-95e9-42e3-89b2-ebca91252734
      version: -1
      name: Validate Error type
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - '10'
      "yes":
      - '8'
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: endWith
          left:
            value:
              simple: PreviousTaskOutput
            iscontext: true
          right:
            value:
              simple: (read timeout=10)
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '12':
    id: '12'
    taskid: 7d97279e-139d-4fb2-81b6-daf54d96dae3
    type: regular
    task:
      id: 7d97279e-139d-4fb2-81b6-daf54d96dae3
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - '16'
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '13':
    id: '13'
    taskid: 129895a3-fb9d-4360-8a4f-44005012e64c
    type: regular
    task:
      id: 129895a3-fb9d-4360-8a4f-44005012e64c
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: cve-latest did not return 30 last entires
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '14':
    id: '14'
    taskid: 70128340-d385-4685-8862-ae251ac9b633
    type: regular
    task:
      id: 70128340-d385-4685-8862-ae251ac9b633
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '15':
    id: '15'
    taskid: 9b8dd13a-c897-48b8-88c8-66a15b060acd
    type: condition
    task:
      id: 9b8dd13a-c897-48b8-88c8-66a15b060acd
      version: -1
      name: Check cve results
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - '11'
      "yes":
      - '8'
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CVE.ID
            iscontext: true
          right:
            value:
              simple: CVE-2015-6541
      - - operator: isEqualNumber
          left:
            value:
              simple: CVE.CVSS
            iscontext: true
          right:
            value:
              simple: "6.8"
      - - operator: isEqualString
          left:
            value:
              simple: CVE.Published
            iscontext: true
          right:
            value:
              simple: 2016-04-08T14:59:00
      - - operator: isEqualString
          left:
            value:
              simple: CVE.Modified
            iscontext: true
          right:
            value:
              simple: 2016-04-11T17:44:00
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
description: ''
fromversion: 4.1.0
