id: TIM - Run Enrichment For All Tagged Indicators
version: -1
fromversion: 5.5.0
name: TIM - Run Enrichment For All Tagged Indicators
description: |-
  This playbook processes indicators by enriching indicators
    based on the indicator feed's reputation, as specified in the playbook
    inputs. This playbook needs to be used with caution as it might use up the user
    enrichment integration's API license when running enrichment for large amounts of
    indicators.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: c35496fc-9821-4385-87b0-d6cfe3ee51dd
    type: start
    task:
      id: c35496fc-9821-4385-87b0-d6cfe3ee51dd
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
      - "5"
      - "11"
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 490,
          "y": -50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 31f60308-885a-45f1-88b6-dbaa0cc81e8a
    type: playbook
    task:
      id: 31f60308-885a-45f1-88b6-dbaa0cc81e8a
      version: -1
      name: TIM - Run Enrichment For IP Indicators
      description: |-
        This playbook processes indicators enriching indicators based on the indicator feed's reputation, as specified in the
                playbook inputs. The playbook ignores indicators that have been tagged by other processing playbooks.
      playbookName: TIM - Run Enrichment For IP Indicators
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      EnrichBadIndicators: {}
      EnrichGoodIndicators: {}
      EnrichSuspiciousIndicators: {}
      EnrichUnkownIndicaotrs: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": -40,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a4b14156-3381-4b85-8da1-8f24b8933437
    type: playbook
    task:
      id: a4b14156-3381-4b85-8da1-8f24b8933437
      version: -1
      name: TIM - Run Enrichment For Hash Indicators
      description: |-
        This playbook processes indicators enriching indicators based on the indicator feed's reputation, as specified in the
                playbook inputs. The playbook ignores indicators that have been tagged by other processing playbooks.
      playbookName: TIM - Run Enrichment For Hash Indicators
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      EnrichBadIndicators: {}
      EnrichGoodIndicators: {}
      EnrichSuspiciousIndicators: {}
      EnrichUnkownIndicaotrs: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 960,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 48df9295-ef14-48d6-83d8-19650d3969a1
    type: condition
    task:
      id: 48df9295-ef14-48d6-83d8-19650d3969a1
      version: -1
      name: Are there IP indicators?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: playbookQuery.indicator_type
            iscontext: true
          right:
            value:
              simple: IP
    view: |-
      {
        "position": {
          "x": 230,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: b72fe617-e279-4b81-82f7-e9a3e1d03f31
    type: condition
    task:
      id: b72fe617-e279-4b81-82f7-e9a3e1d03f31
      version: -1
      name: Are there file hash indicators?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: playbookQuery.indicator_type
            iscontext: true
          right:
            value:
              simple: File
    view: |-
      {
        "position": {
          "x": 730,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: fb9ebb6e-ae47-4d00-8634-475d12488e79
    type: title
    task:
      id: fb9ebb6e-ae47-4d00-8634-475d12488e79
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 61b4a737-d01e-41eb-8d57-ec6868d14db3
    type: playbook
    task:
      id: 61b4a737-d01e-41eb-8d57-ec6868d14db3
      version: -1
      name: TIM - Run Enrichment For Domain Indicators
      playbookName: TIM - Run Enrichment For Domain Indicators
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 1540,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 074b1422-b0db-4d6b-865e-4efd8af74af0
    type: playbook
    task:
      id: 074b1422-b0db-4d6b-865e-4efd8af74af0
      version: -1
      name: TIM - Run Enrichment For Url Indicators
      playbookName: TIM - Run Enrichment For Url Indicators
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "12"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": -650,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: fda3e1e0-e491-41b5-8249-9fae836c7df6
    type: condition
    task:
      id: fda3e1e0-e491-41b5-8249-9fae836c7df6
      version: -1
      name: Are there Url indicators?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: playbookQuery.indicator_type
            iscontext: true
          right:
            value:
              simple: URL
    view: |-
      {
        "position": {
          "x": -480,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: b2a691a9-d208-4e56-8a43-76561642b3aa
    type: condition
    task:
      id: b2a691a9-d208-4e56-8a43-76561642b3aa
      version: -1
      name: Are there domain indicators?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "8"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: playbookQuery.indicator_type
            iscontext: true
          right:
            value:
              simple: Domain
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: fa62efd4-3166-431f-8dfd-1c93decee962
    type: regular
    task:
      id: fa62efd4-3166-431f-8dfd-1c93decee962
      version: -1
      name: Remove tag from all enriched indicators
      description: Remove requires enrichment tag from indicators
      script: Builtin|||removeIndicatorField
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: requires_enrichment
      indicatorsValues:
        complex:
          root: ${playbookQuery
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: playbookQuery.CustomFields.tags
                iscontext: true
              right:
                value:
                  simple: requires_enrichment
          accessor: value}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 230,
          "y": 560
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 855,
        "width": 2570,
        "x": -650,
        "y": -50
      }
    }
  }
inputs:
- key: ""
  value: {}
  required: false
  description: ""
  playbookInputQuery:
    query: tags:requires_enrichment
    queryEntity: indicators
    results: null
    daterange:
      fromdate: 0001-01-01T00:00:00Z
      todate: 0001-01-01T00:00:00Z
      period:
        by: ""
        byto: ""
        byfrom: ""
        tovalue: null
        fromvalue: null
        field: ""
      fromdatelicenseval: 0001-01-01T00:00:00Z
    runFromLastJobTime: false
outputs: []
quiet: true
tests:
- No test