id: Detonate File - ThreatStream
version: -1
name: Detonate File - ThreatStream
fromversion: 4.5.0
description: Detonate one or more files using the Anomali ThreatStream v2 integration.
  This playbook returns relevant reports to the War Room and file reputations to the
  context data.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d3336e07-92bc-4ba0-8d83-cca11db1c563
    type: start
    task:
      id: d3336e07-92bc-4ba0-8d83-cca11db1c563
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: a547fbf3-15c1-45d3-819a-5671ad61f02c
    type: condition
    task:
      id: a547fbf3-15c1-45d3-819a-5671ad61f02c
      version: -1
      name: Is  Anomali ThreatStream v2 enabled?
      description: Verify that there is a valid instance of Anomali ThreatStream v2
        is enabled
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Anomali ThreatStream v2
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: dd2deda1-6796-4731-8269-1cb550ae7cac
    type: title
    task:
      id: dd2deda1-6796-4731-8269-1cb550ae7cac
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 7a366a19-205e-48d3-8609-15080c605210
    type: regular
    task:
      id: 7a366a19-205e-48d3-8609-15080c605210
      version: -1
      name: ThreatStream Get Report
      description: Returns report of file or URL that was submitted to sandbox.
      script: '|||threatstream-analysis-report'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      report_id:
        simple: ${ThreatStream.Analysis.ReportID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: f730b064-98ad-42a3-82ac-7d2c62b15006
    type: regular
    task:
      id: f730b064-98ad-42a3-82ac-7d2c62b15006
      version: -1
      name: Set file to context
      description: Set the file object into context.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    scriptarguments:
      append: {}
      key:
        simple: File
      value:
        complex:
          root: inputs.File
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: de76c4b7-d583-48c0-86c6-d91370ed2d03
    type: playbook
    task:
      id: de76c4b7-d583-48c0-86c6-d91370ed2d03
      version: -1
      name: GenericPolling
      description: |-
        Use as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continually running the command in Step #2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        complex:
          root: ThreatStream
          accessor: Analysis.ReportID
      Interval:
        complex:
          root: inputs.Interval
      PollingCommandArgName:
        simple: report_id
      PollingCommandName:
        simple: threatstream-get-analysis-status
      Timeout:
        complex:
          root: inputs.Timeout
      dt:
        simple: ThreatStream.Analysis(val.Status=='processing').ReportID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 36a2f7db-306d-4708-8633-62af8b8814fc
    type: condition
    task:
      id: 36a2f7db-306d-4708-8633-62af8b8814fc
      version: -1
      name: Is there a file to detonate?
      description: Checks whether there's a file to detonate - if not then the detonation
        is skipped
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: inputs.File
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 60cfab37-2230-44c2-88ac-849ca43481e8
    type: condition
    task:
      id: 60cfab37-2230-44c2-88ac-849ca43481e8
      version: -1
      name: Is the file size bigger than 0?
      description: Check that fail size is bigger than 0
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "20"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: greaterThan
          left:
            value:
              simple: File.Size
            iscontext: true
          right:
            value:
              simple: "0"
    view: |-
      {
        "position": {
          "x": 275,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: b431baa2-7947-40ca-8a67-50ae172d56e1
    type: regular
    task:
      id: b431baa2-7947-40ca-8a67-50ae172d56e1
      version: -1
      name: ThreatStream Upload File
      description: Detonates file or URL to the ThreatStream-hosted Sandbox.
      script: '|||threatstream-submit-to-sandbox'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      detail:
        simple: ${inputs.Tags}
      premium_sandbox:
        simple: ${inputs.PremiumSandbox}
      report_platform:
        simple: ${inputs.VM}
      submission_classification:
        simple: ${inputs.SubmissionClassification}
      submission_type:
        simple: file
      submission_value:
        simple: ${inputs.File.EntryID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 387.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "5_6_#default#": 0.44
    },
    "paper": {
      "dimensions": {
        "height": 1435,
        "width": 717.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: File
  value:
    complex:
      root: File
  required: false
  description: File object of the file to detonate.
- key: VM
  value: {}
  required: false
  description: The VM to use (string)
- key: SubmissionClassification
  value: {}
  required: false
  description: Classification of the Sandbox submission.
- key: PremiumSandbox
  value: {}
  required: false
  description: Specify whether the premium sandbox should be used for detonation.
- key: Tags
  value: {}
  required: false
  description: A comma-separated list of tags applied to this sample.
- key: Interval
  value: {}
  required: false
  description: Polling frequency - how often the polling command should run (minutes)
- key: Timeout
  value: {}
  required: false
  description: How much time to wait before a timeout occurs (minutes)
outputs:
- contextPath: File.Malicious
  description: The File malicious description
  type: unknown
- contextPath: File.Malicious.Vendor
  description: For malicious files, the vendor that made the decision
  type: string
- contextPath: File.Type
  description: File type e.g. "PE"
  type: string
- contextPath: File.Size
  description: File size
  type: number
- contextPath: File.MD5
  description: MD5 hash of the file
  type: string
- contextPath: File.Name
  description: Filename
  type: string
- contextPath: File.SHA1
  description: SHA1 hash of the file
  type: string
- contextPath: File
  description: The File object
  type: unknown
- contextPath: File.SHA256
  description: SHA256 hash of the file
  type: string
- contextPath: DBotScore
  description: The DBotScore object
  type: unknown
- contextPath: DBotScore.Indicator
  description: The indicator we tested
  type: string
- contextPath: DBotScore.Type
  description: The type of the indicator
  type: string
- contextPath: DBotScore.Vendor
  description: Vendor used to calculate the score
  type: string
- contextPath: DBotScore.Score
  description: The actual score
  type: number
tests:
  - No test