id: PAN-OS DAG Configuration
version: -1
name: PAN-OS DAG Configuration
fromversion: 4.5.0
description: "This playbook utilizes the Dynamic Address Group capability of PAN-OS\nDAG
  allows the analyst to create a rule once with the group as the source/destination
  and add IPs dynamically without the need to commit the configuration every time.\n\nThe
  playbook checks if the given tag already exists, and if yes then it adds the IP
  to the tag.\n\nIf the tag does not exist, it creates a new address group with the
  given tag and a matching rule and will commit the configuration. \n"
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 24fcd4ca-bf27-4bc1-86fd-569548dd22ba
    type: start
    task:
      id: 24fcd4ca-bf27-4bc1-86fd-569548dd22ba
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 320fbaaa-b322-4d39-8549-2663d87df56e
    type: condition
    task:
      id: 320fbaaa-b322-4d39-8549-2663d87df56e
      version: -1
      name: Is PAN-OS integration enabled?
      description: Checks whether the integration is enabled and configured
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "5"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Panorama
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 2235c4df-c6d7-40ff-8ac3-6c43b66fe753
    type: regular
    task:
      id: 2235c4df-c6d7-40ff-8ac3-6c43b66fe753
      version: -1
      name: List Address Groups
      description: Lists all the address groups in PAN-OS
      script: '|||panorama-list-address-groups'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 367.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: cf23bd70-8c0b-469e-8872-6b294bf3e9be
    type: condition
    task:
      id: cf23bd70-8c0b-469e-8872-6b294bf3e9be
      version: -1
      name: Check if tag exists in address groups
      description: Looks up the given tag in the address groups
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              complex:
                root: Panorama
                accessor: AddressGroups.Match
                transformers:
                - operator: Stringify
                - operator: join
                  args:
                    separator:
                      value:
                        simple: ' '
            iscontext: true
          right:
            value:
              simple: inputs.tag_name
            iscontext: true
          ignorecase: true
    view: |-
      {
        "position": {
          "x": 367.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 3b6960c6-2d5f-4417-876e-86aced2808cc
    type: regular
    task:
      id: 3b6960c6-2d5f-4417-876e-86aced2808cc
      version: -1
      name: Register tag on an IP
      description: Registers IP addresses to a tag
      script: Panorama|||panorama-register-ip-tag
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      IPs:
        simple: ${inputs.ip_list}
      persistent: {}
      tag:
        simple: ${inputs.tag_name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: ee06ca45-8577-4b16-8911-2ac2560b2142
    type: title
    task:
      id: ee06ca45-8577-4b16-8911-2ac2560b2142
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: bd80e411-5bc3-48b1-850b-362bc9d508a1
    type: regular
    task:
      id: bd80e411-5bc3-48b1-850b-362bc9d508a1
      version: -1
      name: Create Address Group
      description: Creates an address group; "static" or "dynamic"
      script: Panorama|||panorama-create-address-group
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      addresses: {}
      description: {}
      match:
        simple: ${inputs.tag_name}
      name:
        simple: ${inputs.address_group_name}
      type:
        simple: dynamic
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: bcc6e979-2515-4aa2-8a8d-5c95f4b26b42
    type: regular
    task:
      id: bcc6e979-2515-4aa2-8a8d-5c95f4b26b42
      version: -1
      name: Create Block Rule
      description: Creates a custom block policy rule
      script: Panorama|||panorama-custom-block-rule
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      direction:
        simple: both
      log_forwarding: {}
      object_type:
        simple: address-group
      object_value:
        simple: ${inputs.address_group_name}
      pre_post:
        simple: pre-rulebase
      rulename:
        simple: ${inputs.rule_name}
      target: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 19cf90dc-4544-47e9-809f-38090341f269
    type: regular
    task:
      id: 19cf90dc-4544-47e9-809f-38090341f269
      version: -1
      name: Manually commit
      description: Allows the analyst to manually commit the changes. will be operational
        if auto-commit is false
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1050,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 2bd82322-f586-4e9c-881c-f4385d43d012
    type: playbook
    task:
      id: 2bd82322-f586-4e9c-881c-f4385d43d012
      version: -1
      name: Pan-OS-Commit-Configuration
      description: ""
      playbookName: Pan-OS Commit Configuration
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 610,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 31f00bc1-3fee-484e-8189-a0a011fd5f71
    type: condition
    task:
      id: 31f00bc1-3fee-484e-8189-a0a011fd5f71
      version: -1
      name: Is auto commit defined?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "15"
      "yes":
      - "16"
    scriptarguments:
      left:
        simple: ${inputs.auto_commit}
      right:
        simple: "Yes"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 705,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "17_15_#default#": 0.4,
      "17_16_yes": 0.34,
      "1_5_#default#": 0.1,
      "3_4_yes": 0.47,
      "3_6_#default#": 0.65
    },
    "paper": {
      "dimensions": {
        "height": 1925,
        "width": 1380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: tag_name
  value: {}
  required: true
  description: the name of the tag that we wish to add to PAN-OS
- key: ip_list
  value: {}
  required: true
  description: the list of the IPs that we are wishing to block
- key: address_group_name
  value: {}
  required: true
  description: the name of the group that will be created in case the tag does not
    exist
- key: rule_name
  value: {}
  required: false
  description: the informative name of the rule in PAN-OS
- key: auto_commit
  value:
    simple: "Yes"
  required: false
  description: Should the rule be committed automatically or manually?
outputs: []
