id: DBot Create Phishing Classifier V2 Job
version: -1
name: DBot Create Phishing Classifier V2 Job
description: 'Train the phishing machine learning model. This playbook should be used
  as job, to run repeatedly, for example every week. '
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3f296bee-5970-4a35-819b-30ace9905ff7
    type: start
    task:
      id: 3f296bee-5970-4a35-819b-30ace9905ff7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f2153861-94b2-4de6-8883-546b3e4dc5b9
    type: title
    task:
      id: f2153861-94b2-4de6-8883-546b3e4dc5b9
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: a0577456-3576-460d-8ede-15c6569f611a
    type: regular
    task:
      id: a0577456-3576-460d-8ede-15c6569f611a
      version: -1
      name: Close incident
      description: Close the investigation - we want to close the incident if the
        playbook successfully finished.
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: cd901cee-98fa-416b-8e39-519218a516ea
    type: regular
    task:
      id: cd901cee-98fa-416b-8e39-519218a516ea
      version: -1
      name: Clean context
      description: Clear all context data
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 70b1ec08-66fc-4e25-8f77-7fd2aef4ef24
    type: playbook
    task:
      id: 70b1ec08-66fc-4e25-8f77-7fd2aef4ef24
      version: -1
      name: DBot Create Phishing Classifier V2
      playbookName: DBot Create Phishing Classifier V2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      dedupThreshold:
        simple: "0.99"
      emailSubjectKey:
        simple: emailsubject
      emailTagKey:
        simple: emailclassification
      emailTextKey:
        simple: details
      hashSeed: {}
      historicalDataFileListName: {}
      incidentTypes:
        simple: Phishing
      incidentsQuery: {}
      maxIncidentsToFetchOnTraining:
        simple: "3000"
      modelName:
        simple: phishing_model
      modelTargetAccuracy:
        simple: "0.8"
      overrideModel:
        simple: "true"
      phishingLabels:
        simple: '*'
      removeShortTextThreshold:
        simple: "15"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: "4.5.0"
tests:
  - Create Phishing Classifier V2 ML Test