elasticcommonfields: {}
id: ArcSight Add Url Indicators
version: -1
fromversion: 5.5.0
name: ArcSight Add Url Indicators
description: The playbook queries indicators based on the specified tags and uploads the to the ArcSight Active List in the inputs.
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: '1'
    type: start
    task:
      elasticcommonfields: {}
      id: '1'
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '18'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 340,
          "y": -330
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '3':
    id: '3'
    taskid: 7701955f-2902-40e4-81db-0249b7febfcd
    type: title
    task:
      elasticcommonfields: {}
      id: 7701955f-2902-40e4-81db-0249b7febfcd
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 340,
          "y": 1190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '8':
    id: '8'
    taskid: 856f9240-8c51-4b67-8e07-4d3c074257b8
    type: condition
    task:
      elasticcommonfields: {}
      id: 856f9240-8c51-4b67-8e07-4d3c074257b8
      version: -1
      name: Is ArcSight Enabled?
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '30'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: ArcSight ESM v2
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                accessor: brand
            iscontext: true
    view: |-
      {
        "position": {
          "x": 590,
          "y": 240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '18':
    id: '18'
    taskid: acd0ee27-a2f4-40eb-86e3-1df4f520f545
    type: condition
    task:
      elasticcommonfields: {}
      id: acd0ee27-a2f4-40eb-86e3-1df4f520f545
      version: -1
      name: Are there filtered results?
      description: Checks whether the specified item is in a list. The default list
        is the Demisto Indicators Whitelist.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '8'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: playbookQuery.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 340,
          "y": -170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '30':
    id: '30'
    taskid: 67c1c3a0-3e92-472b-8f7b-c444a52c1bf1
    type: condition
    task:
      elasticcommonfields: {}
      id: 67c1c3a0-3e92-472b-8f7b-c444a52c1bf1
      version: -1
      name: Is there an ArcSight Url active List?
      type: condition
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#default#':
      - '3'
      'yes':
      - '59'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.ArcSightUrlActiveListID
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.ArcsightUrlValueFieldName
            iscontext: true
    view: |-
      {
        "position": {
          "x": 700,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  '59':
    id: '59'
    taskid: 80264d4e-d799-4040-8b50-5e96a5daa2fe
    type: regular
    task:
      elasticcommonfields: {}
      id: 80264d4e-d799-4040-8b50-5e96a5daa2fe
      version: -1
      name: Add Url to ArcSight Active list
      description: Adds new entries to the Active List.
      script: ArcSight ESM v2|||as-add-entries
      type: regular
      iscommand: true
      brand: ArcSight ESM v2
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      entries:
        complex:
          root: playbookQuery
          accessor: value
          transformers:
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: (.*)
              replaceWith:
                value:
                  simple: $1
          - operator: concat
            args:
              prefix:
                value:
                  simple: ':'
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: inputs.ArcsightUrlValueFieldName
                iscontext: true
              suffix: {}
          - operator: join
            args:
              separator:
                value:
                  simple: '"},{"'
          - operator: replaceMatch
            args:
              regex:
                value:
                  simple: ':'
              replaceWith:
                value:
                  simple: '":"'
          - operator: concat
            args:
              prefix:
                value:
                  simple: '[{"'
              suffix:
                value:
                  simple: '"}]'
      resourceId:
        simple: ${inputs.ArcSightUrlActiveListID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 700,
          "y": 940
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1585,
        "width": 740,
        "x": 340,
        "y": -330
      }
    }
  }
inputs:
- key: ArcSightUrlActiveListID
  value: {}
  required: false
  description: ID the the Url Active List resource as appears in the ArcSight UI.
  playbookInputQuery: null
- key: ArcsightUrlValueFieldName
  value: {}
  required: false
  description: The name of the Active List field to insert the Url value to.
  playbookInputQuery: null
- key: ''
  value: {}
  required: false
  description: ''
  playbookInputQuery:
    query: ''
    queryEntity: indicators
    results: null
    daterange:
      fromdate: 0001-01-01 00:00:00
      todate: 0001-01-01 00:00:00
      period:
        by: ''
        byto: ''
        byfrom: ''
        tovalue: null
        fromvalue: null
        field: ''
      fromdatelicenseval: 0001-01-01 00:00:00
    runFromLastJobTime: false
outputs: []
sourceplaybookid: 4dd3e7d3-3703-44e8-80d6-513874da3866
quiet: true
tests:
- No test