id: PAN-OS Log Forwarding Setup
version: -1
name: PAN-OS Log Forwarding Setup
fromversion: 4.0.0
description: Sets up log forwarding for all rules in PAN-OS.\ngoes over all rules either pre/post rulebase and adds the given log forwarding object to it.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7e873ae1-3b70-44c6-88c7-02412b36edd8
    type: start
    description: ""
    task:
      id: 7e873ae1-3b70-44c6-88c7-02412b36edd8
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 149cb50b-1ec6-4788-8ecb-9c385f4df08f
    type: title
    task:
      id: 149cb50b-1ec6-4788-8ecb-9c385f4df08f
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 7c8daa69-572b-46ef-8416-8982be8bb498
    type: regular
    task:
      id: 7c8daa69-572b-46ef-8416-8982be8bb498
      version: -1
      name: List Rules
      description: Lists all rules in PAN-OS, with either pre or post rulebase.
      script: '|||panorama-list-rules'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      pre_post:
        simple: ${inputs.pre-post-rulebase}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 0c4e55d9-b9a6-4533-8b1b-2bd55ad7b137
    type: regular
    task:
      id: 0c4e55d9-b9a6-4533-8b1b-2bd55ad7b137
      version: -1
      name: Edit rule - add log forwarding
      description: Edits the rule, adds or overrides the log forwarding object
      script: '|||panorama-edit-rule'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      element_to_change:
        simple: log-forwarding
      element_value:
        simple: ${inputs.log-forwarding-name}
      pre_post:
        simple: ${inputs.pre-post-rulebase}
      rulename:
        simple: ${Panorama.SecurityRule.Name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 382555b7-9ed7-483b-8545-d81f4ecb7e2e
    type: condition
    task:
      id: 382555b7-9ed7-483b-8545-d81f4ecb7e2e
      version: -1
      name: Is auto-commit defined?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "no":
      - "6"
      "yes":
      - "5"
    scriptarguments:
      left:
        simple: ${inputs.auto_commit}
      right:
        simple: "yes"
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: b25ece8d-ac98-42e6-8812-b68efdc37d02
    type: playbook
    task:
      id: b25ece8d-ac98-42e6-8812-b68efdc37d02
      version: -1
      name: PAN-OS Commit Configuration
      description: ""
      playbookName: PAN-OS Commit Configuration
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 1c1fc4c9-32a2-4caa-8030-b9d6732f4eeb
    type: regular
    task:
      id: 1c1fc4c9-32a2-4caa-8030-b9d6732f4eeb
      version: -1
      name: Manually commit
      description: Allows the analyst to manually commit the changes. This will be operational if auto-commit is "false".
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "4_5_yes": 0.46,
      "4_6_no": 0.6
    },
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: log-forwarding-name
  value:
    simple: log_forwarding_101
  required: true
  description: the name of the log-forwarding object that will be attached to all
    the rules
- key: auto_commit
  value:
    simple: "yes"
  required: false
  description: Should the rule be committed automatically or manually?
- key: pre-post-rulebase
  value:
    simple: pre-rulebase
  required: true
  description: either pre-rulebase or post-rulebase according to rule structure
outputs: []
