id: ExtraHop - Get Peers by Host
version: -1
fromversion: 4.5.0
name: ExtraHop - Get Peers by Host
description: Given a host, the playbook will retrieve the peer network devices that
  communicated with that host in a given time range.  In addition to a list of peers
  and protocols (sorted by bytes) the playbook returns a link to the ExtraHop Live
  Activity Map to visualize the peer relationships.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 71394f2c-bc76-4885-8bab-b55ce0094789
    type: start
    task:
      id: 71394f2c-bc76-4885-8bab-b55ce0094789
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f4953d89-2219-4d74-8acf-d819728d0ac9
    type: title
    task:
      id: f4953d89-2219-4d74-8acf-d819728d0ac9
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 70,
          "y": 1220
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 416da4b1-f8f7-4845-82c0-cb389d224631
    type: regular
    task:
      id: 416da4b1-f8f7-4845-82c0-cb389d224631
      version: -1
      name: ExtraHop Get Peers
      description: Get the list of all of the peers that communicated with the given
        host in the specified time range.
      script: 'ExtraHop v2|||extrahop-get-peers'
      type: regular
      iscommand: true
      brand: ExtraHop v2
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      ip_or_id:
        simple: ${ExtraHop.Device.Id}
      peer_role: {}
      protocol: {}
      query_from:
        complex:
          root: inputs.from_time
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: inputs.from_time
                iscontext: true
          transformers:
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
      query_until:
        complex:
          root: inputs.until_time
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: inputs.until_time
                iscontext: true
          transformers:
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 360,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 62105272-7fd7-4799-87e8-e41c0ade44c8
    type: regular
    task:
      id: 62105272-7fd7-4799-87e8-e41c0ade44c8
      version: -1
      name: ExtraHop Device Search
      description: Search for the device within ExtraHop using the provided name,
        IP address, and MAC address.
      script: 'ExtraHop v2|||extrahop-device-search'
      type: regular
      iscommand: true
      brand: ExtraHop v2
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      active_from: {}
      active_until: {}
      activity: {}
      discover_time: {}
      ip:
        simple: ${inputs.ip}
      l3_only: {}
      limit:
        simple: "1"
      mac:
        simple: ${inputs.mac}
      match_type: {}
      name:
        simple: ${inputs.name}
      operator: {}
      role: {}
      software: {}
      tag: {}
      vendor: {}
      vlan: {}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 360,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: fcfbff68-d288-45ef-89b8-dd44d6d8a336
    type: condition
    task:
      id: fcfbff68-d288-45ef-89b8-dd44d6d8a336
      version: -1
      name: Is there a host?
      description: Check if the host information required to search for peers was
        provided.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.name
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              simple: inputs.ip
            iscontext: true
        - operator: isNotEmpty
          left:
            value:
              simple: inputs.mac
            iscontext: true
    view: |-
      {
        "position": {
          "x": 160,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: 281c54f6-e598-4b2a-8eda-cb0291c125e2
    type: condition
    task:
      id: 281c54f6-e598-4b2a-8eda-cb0291c125e2
      version: -1
      name: Found Device?
      description: Check if a device was found.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "3"
      - "16"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              simple: ExtraHop.Device
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 360,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: 076a2991-f4ba-4e39-8f03-5f039fa69321
    type: condition
    task:
      id: 076a2991-f4ba-4e39-8f03-5f039fa69321
      version: -1
      name: Is ExtraHop Reveal(x) enabled?
      description: Checks if there is an active instance of the ExtraHop Reveal(x)
        integration enabled.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "9"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: ExtraHop v2
          - - operator: isEqualString
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: bd13a6e0-af76-4c8a-8940-9acbe86c4926
    type: regular
    task:
      id: bd13a6e0-af76-4c8a-8940-9acbe86c4926
      version: -1
      name: ExtraHop Get Activity Map
      description: Get a link to a live activity map for the given device in the specified
        time range.
      script: 'ExtraHop v2|||extrahop-get-activity-map'
      type: regular
      iscommand: true
      brand: ExtraHop v2
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      from_time:
        complex:
          root: inputs.from_time
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: inputs.from_time
                iscontext: true
      ip_or_id:
        simple: ${ExtraHop.Device.Id}
      peer_role: {}
      protocol: {}
      time_interval: {}
      until_time:
        complex:
          root: inputs.until_time
          filters:
          - - operator: isNotEmpty
              left:
                value:
                  simple: inputs.until_time
                iscontext: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 760,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "11_16_yes": 0.29,
      "11_2_#default#": 0.28,
      "11_3_yes": 0.58,
      "15_2_#default#": 0.29,
      "15_9_yes": 0.53,
      "9_2_#default#": 0.24,
      "9_7_yes": 0.44
    },
    "paper": {
      "dimensions": {
        "height": 1235,
        "width": 1090,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: name
  value: {}
  required: false
  description: The name of the device. This searches for matches on all ExtraHop name
    fields (DHCP, DNS, NetBIOS, Cisco Discovery Protocol, etc).
- key: ip
  value: {}
  required: false
  description: The IP address of the device.
- key: mac
  value: {}
  required: false
  description: The MAC address of the device.
- key: from_time
  value: {}
  required: false
  description: The beginning timestamp of the time range the playbook will use to
    search, expressed in seconds since the epoch.
- key: until_time
  value: {}
  required: false
  description: The ending timestamp of the time range the playbook will use to search,
    expressed in seconds since the epoch.
outputs: []
tests:
- ExtraHop_v2-Test