id: Digital Defense FrontlineVM - PAN-OS block assets
version: -1
name: Digital Defense FrontlineVM - PAN-OS block assets
description: This playbook will pull Panorama queried threat logs and check for any
  correlating assets that are found to have a minimum of high level vulnerabilities.
  If so, it will block the the IP using Panorama's PAN-OS - Block IP and URL - External
  Dynamic List playbook.
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 3af2c27a-a555-4626-80d4-85e692a8263c
    type: start
    task:
      id: 3af2c27a-a555-4626-80d4-85e692a8263c
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '14'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: 8d0120d0-657c-49ff-8552-ada9b349d9b1
    type: regular
    task:
      id: 8d0120d0-657c-49ff-8552-ada9b349d9b1
      version: -1
      name: panorama-query-logs (query threat logs)
      description: Query logs in Panorama.
      script: Panorama|||panorama-query-logs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - '16'
    scriptarguments:
      action: {}
      addr-dst: {}
      addr-src: {}
      filedigest: {}
      log-type:
        simple: threat
      number_of_logs: {}
      port-dst: {}
      query: {}
      rule: {}
      time-generated: {}
      url: {}
      zone-dst: {}
      zone-src: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: 81702d7f-3631-4752-8a6c-0a6239294803
    type: regular
    task:
      id: 81702d7f-3631-4752-8a6c-0a6239294803
      version: -1
      name: panorama-get-logs (retrieve completed log query)
      description: Retrieves the data of a logs query.
      script: Panorama|||panorama-get-logs
      type: regular
      iscommand: true
      brand: Panorama
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      ignore_auto_extract: {}
      job_id:
        simple: ${Panorama.Monitor.JobID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: c3573fa6-14b2-4d52-8bba-81bc68cdd7ca
    type: regular
    task:
      id: c3573fa6-14b2-4d52-8bba-81bc68cdd7ca
      version: -1
      name: frontline-get-vulns (pull high severity vulns from threat source)
      description: Query FrontlineVM for vulnerabilities with a minimum severity of
        'high' found from Panorama's queried log threat source.
      script: Digital Defense FrontlineVM|||frontline-get-vulns
      type: regular
      iscommand: true
      brand: Digital Defense FrontlineVM
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      host_id: {}
      ip_address:
        simple: ${Panorama.Monitor.Logs.SourceAddress}
      max_days_since_created: {}
      min_days_since_created: {}
      min_severity:
        simple: high
      severity: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '7':
    id: '7'
    taskid: d2483fcc-2591-4d14-8b50-5c3830c24496
    type: condition
    task:
      id: d2483fcc-2591-4d14-8b50-5c3830c24496
      version: -1
      name: Check if vulns found.
      description: Check results of previous task.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '9'
      'yes':
      - '8'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              simple: FrontlineVM.Vulns
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '8':
    id: '8'
    taskid: 2b4e44d3-d2f7-4fa8-8747-d333567a389c
    type: regular
    task:
      id: 2b4e44d3-d2f7-4fa8-8747-d333567a389c
      version: -1
      name: Critical vulnerabilities exist within Frontline.Cloud from PAN OS threat
        logs.
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '11'
    scriptarguments:
      value:
        simple: 'Asset found to have critical level vulnerabilities within Frontline.Cloud:
          ${Panorama.Monitor.Logs.SourceAddress}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '9':
    id: '9'
    taskid: a66a80d3-82d2-4c28-815b-06de2c64525d
    type: regular
    task:
      id: a66a80d3-82d2-4c28-815b-06de2c64525d
      version: -1
      name: No critical vulnerabilities found from PAN OS threat logs.
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ''
    scriptarguments:
      value:
        simple: 'Critical vulnerabilities not found within Frontline.Cloud for given
          asset: ${Panorama.Monitor.Logs.SourceAddress}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '11':
    id: '11'
    taskid: 92380cc5-adee-4bc5-8d15-7b25da58d431
    type: playbook
    task:
      id: 92380cc5-adee-4bc5-8d15-7b25da58d431
      version: -1
      name: PAN-OS - Block IP and URL - External Dynamic List
      description: ''
      playbookName: PAN-OS - Block IP and URL - External Dynamic List
      type: playbook
      iscommand: false
      brand: ''
    scriptarguments:
      AutoCommit:
        simple: 'No'
      EDLServerIP: {}
      IP:
        complex:
          root: FrontlineVM
          accessor: IPList
          transformers:
          - operator: uniq
      IPListName:
        simple: Demisto Remediation - IP EDL
      LogForwarding: {}
      URL: {}
      URLListName:
        simple: Demisto Remediation - URL EDL
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ''
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '14':
    id: '14'
    taskid: 9c42b1ba-25c9-4ead-8287-274187e4b6c0
    type: regular
    task:
      id: 9c42b1ba-25c9-4ead-8287-274187e4b6c0
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '16':
    id: '16'
    taskid: 40ffabd8-fed9-4b39-8b85-37bf66787161
    type: regular
    task:
      id: 40ffabd8-fed9-4b39-8b85-37bf66787161
      version: -1
      name: GenericPolling
      description: Called by the GenericPolling playbook, schedules the polling task.
      scriptName: ScheduleGenericPolling
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '17'
    scriptarguments:
      additionalPollingCommandArgNames: {}
      additionalPollingCommandArgValues: {}
      dt:
        simple: Panorama.Monitor(val.Status != 'Pending').JobID
      ids:
        simple: ${Panorama.Monitor.JobID}
      interval:
        simple: '1'
      playbookId: {}
      pollingCommand:
        simple: panorama-check-logs-status
      pollingCommandArgName:
        simple: job_id
      tag: {}
      timeout:
        simple: '60'
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '17':
    id: '17'
    taskid: 15f1f59b-a7a2-4abe-879d-e562e1ae0933
    type: regular
    task:
      id: 15f1f59b-a7a2-4abe-879d-e562e1ae0933
      version: -1
      name: panorama-check-logs-status
      description: Command to check panorama log status.
      script: '|||panorama-check-logs-status'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      job_id:
        simple: ${Panorama.Monitor.JobID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1640,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
