id: d4dcf130-a805-4345-8988-d47aa1b53e35
version: -1
name: Default IronDefense Example
description: Default playbook, Enrich indicators in incident using one or more integrations
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: cc3f425b-e52e-4d47-80a4-b8c711288cc0
    type: start
    task:
      id: cc3f425b-e52e-4d47-80a4-b8c711288cc0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
      - "20"
      - "23"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: b1b0cb3c-57a0-4d7c-8df9-a9431ec3dd49
    type: condition
    task:
      id: b1b0cb3c-57a0-4d7c-8df9-a9431ec3dd49
      version: -1
      name: Should perform enrichment?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "16"
      "yes":
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 0cb06894-5c0c-4413-8f65-5ba8e3f4de4a
    type: regular
    task:
      id: 0cb06894-5c0c-4413-8f65-5ba8e3f4de4a
      version: -1
      name: Choose analyst
      scriptName: AssignAnalystToIncident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      assignBy:
        simple: random
      email: {}
      roles: {}
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1915
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: b2bc18e1-0079-4838-89aa-f12180105d9d
    type: title
    task:
      id: b2bc18e1-0079-4838-89aa-f12180105d9d
      version: -1
      name: Enrich indicators
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: b9a8a4f4-6583-4d6a-8f03-e4f822d6bac0
    type: playbook
    task:
      id: b9a8a4f4-6583-4d6a-8f03-e4f822d6bac0
      version: -1
      name: ""
      playbookName: Extract Indicators - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 47afb7d2-bb8e-4f0b-8cda-c3c5667e0934
    type: playbook
    task:
      id: 47afb7d2-bb8e-4f0b-8cda-c3c5667e0934
      version: -1
      name: ""
      playbookName: Entity Enrichment - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 5a29122f-b1f5-4c1a-8517-f656dd796e4b
    type: playbook
    task:
      id: 5a29122f-b1f5-4c1a-8517-f656dd796e4b
      version: -1
      name: ""
      playbookName: Calculate Severity - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: f9b0c31b-e22b-468b-8f56-0d552d196275
    type: regular
    task:
      id: f9b0c31b-e22b-468b-8f56-0d552d196275
      version: -1
      name: Manually review the incident
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 042198aa-0de5-4739-8a3a-042af87a9a65
    type: regular
    task:
      id: 042198aa-0de5-4739-8a3a-042af87a9a65
      version: -1
      name: Close Investigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes:
        simple: Default Enrichment Playbook
      closeReason: {}
      id: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1135,
          "y": 2615
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: be7e215a-bbbd-4796-8b3e-bb704108ad61
    type: collection
    task:
      id: be7e215a-bbbd-4796-8b3e-bb704108ad61
      version: -1
      name: Rate the Incident
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2265
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject:
        simple: Rate Severity for ${incident.name}
      body:
        simple: Use the web form to rate the severity for this incident.
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: How would you categorize the severity uncovered by this alert?
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - Undecided
        - Benign
        - Suspicious
        - Malicious
        fieldassociated: ""
        placeholder: ""
        tooltip: Select the severity of this incident.
      - id: "1"
        label: ""
        labelarg:
          simple: Was this behavior expected for the entities and/or communication?
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - ""
        - Unexpected
        - Expected
        - Unknown
        fieldassociated: ""
        placeholder: ""
        tooltip: Select the behavior expectation for this incident. Choose "Unknown"
          if the severity is undecided.
      - id: "2"
        label: ""
        labelarg:
          simple: Why do you categorize the incident behavior as marked above?
        required: true
        gridcolumns: []
        defaultrows: []
        type: longText
        options: []
        fieldassociated: ""
        placeholder: 'Example: Bitcoin mining, Advertisements leading to unintentional/unacceptable
          amount of data leakage.'
        tooltip: Describe this incident.
      - id: "3"
        label: ""
        labelarg:
          simple: Share comment with IronDome Community? (Comments marked “Yes” are
            shared across the IronDome Community. Please do not include enterprise
            or personal information in the comments.)
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - ""
        - "No"
        - "Yes"
        fieldassociated: ""
        placeholder: ""
        tooltip: Comments marked “Share Comment with IronDome Community” are shared
          across the IronDome Community. Please do not include enterprise or personal
          information in the comments.
      title: Rate IronDefense Alert Severity
      description: Rate the severity of ${incident.name}
      sender: Your SOC team
      expired: false
      totalanswers: 0
  "15":
    id: "15"
    taskid: 9ee28fd1-67d8-4bb2-84b3-732fed1c68ae
    type: regular
    task:
      id: 9ee28fd1-67d8-4bb2-84b3-732fed1c68ae
      version: -1
      name: Submit Incident Rating to IronDefense
      script: IronDefense|||irondefense-rate-alert
      type: regular
      iscommand: true
      brand: IronDefense
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id:
        simple: ${incident.labels.id}
      comments:
        simple: ${Rate IronDefense Alert Severity.Answers.2}
      expectation:
        simple: ${Rate IronDefense Alert Severity.Answers.1}
      severity:
        simple: ${Rate IronDefense Alert Severity.Answers.0}
      share_comment_with_irondome:
        simple: ${Rate IronDefense Alert Severity.Answers.3}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 6f0e004b-55ac-44de-853d-615fd149f420
    type: condition
    task:
      id: 6f0e004b-55ac-44de-853d-615fd149f420
      version: -1
      name: Is Domain Blacklisted?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "17"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: incident.destntdomain
            iscontext: true
          right:
            value:
              simple: baddomain.net
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 82500721-1fa9-4bbf-8fde-7ddc4ba79a8d
    type: condition
    task:
      id: 82500721-1fa9-4bbf-8fde-7ddc4ba79a8d
      version: -1
      name: Is Domain Whitelisted?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "19"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: incident.destntdomain
            iscontext: true
          right:
            value:
              simple: gooddomain.net
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: d5341d3c-c9ec-4c7b-8ac9-64dadce0cbdd
    type: regular
    task:
      id: d5341d3c-c9ec-4c7b-8ac9-64dadce0cbdd
      version: -1
      name: Submit Malicious Rating to IronDefense
      script: IronDefense|||irondefense-rate-alert
      type: regular
      iscommand: true
      brand: IronDefense
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id:
        simple: ${incident.labels.id}
      comments:
        simple: This is known malicious activity!
      expectation:
        simple: EXP_UNEXPECTED
      severity:
        simple: SEVERITY_MALICIOUS
      share_comment_with_irondome:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 2f407cba-6776-4e43-8b55-fc588344355a
    type: regular
    task:
      id: 2f407cba-6776-4e43-8b55-fc588344355a
      version: -1
      name: Submit Benign Rating to IronDefense
      script: IronDefense|||irondefense-rate-alert
      type: regular
      iscommand: true
      brand: IronDefense
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id:
        simple: ${incident.labels.id}
      comments:
        simple: This is benign activity.
      expectation:
        simple: EXP_EXPECTED
      severity:
        simple: SEVERITY_BENIGN
      share_comment_with_irondome:
        simple: "false"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 2440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 2b67e6b3-87a2-4f06-8b06-88e359d8e1ee
    type: condition
    task:
      id: 2b67e6b3-87a2-4f06-8b06-88e359d8e1ee
      version: -1
      name: Comment On Alert?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "Yes":
      - "21"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1247.5,
          "y": 2090
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 39ac8d08-9d5e-4957-8673-36fac5544202
    type: collection
    task:
      id: 39ac8d08-9d5e-4957-8673-36fac5544202
      version: -1
      name: Write Comment
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 2265
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject:
        simple: Comment Added to ${incident.name}
      body: null
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: 'Comments:'
        required: true
        gridcolumns: []
        defaultrows: []
        type: longText
        options: []
        fieldassociated: ""
        placeholder: Your Comment Here
        tooltip: ""
      - id: "1"
        label: ""
        labelarg:
          simple: Share comment with IronDome?
        required: false
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - ""
        - "No"
        - "Yes"
        fieldassociated: ""
        placeholder: ""
        tooltip: Share comment with IronDome Community? (Comments marked “Yes” are
          shared across the IronDome Community. Please do not include enterprise or
          personal information in the comments.)
      title: Add Comment to Alert
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
  "22":
    id: "22"
    taskid: f13ba09d-8a3e-4673-81b3-0f459d80ce22
    type: regular
    task:
      id: f13ba09d-8a3e-4673-81b3-0f459d80ce22
      version: -1
      name: Submit Alert Comment to IronDefense
      script: IronDefense|||irondefense-comment-alert
      type: regular
      iscommand: true
      brand: IronDefense
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      alert_id:
        simple: ${incident.labels.id}
      comment:
        simple: ${Add Comment to Alert.Answers.0}
      share_comment_with_irondome:
        simple: "true"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1360,
          "y": 2440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: 4d7a3b1a-3b18-4be2-8796-abc37a4d6714
    type: condition
    task:
      id: 4d7a3b1a-3b18-4be2-8796-abc37a4d6714
      version: -1
      name: Set Alert Status?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "Yes":
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1585,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "25":
    id: "25"
    taskid: 79ab29af-1073-4790-890b-e3ae01b09bcc
    type: collection
    task:
      id: 79ab29af-1073-4790-890b-e3ae01b09bcc
      version: -1
      name: Set the Status
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1472.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: Analyst
      subject:
        simple: Status set for ${incident.name}
      body:
        simple: Use the web form to rate the severity for this incident.
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: What is the status of this alert?
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - Awaiting Review
        - Under Review
        - Closed
        fieldassociated: ""
        placeholder: ""
        tooltip: Select the severity of this incident.
      - id: "1"
        label: ""
        labelarg:
          simple: Comments on status change?
        required: true
        gridcolumns: []
        defaultrows: []
        type: longText
        options: []
        fieldassociated: ""
        placeholder: 'Example: Bitcoin mining, Advertisements leading to unintentional/unacceptable
          amount of data leakage.'
        tooltip: Describe the status change.
      - id: "2"
        label: ""
        labelarg:
          simple: Share comment with IronDome Community? (Comments marked “Yes” are
            shared across the IronDome Community. Please do not include enterprise
            or personal information in the comments.)
        required: true
        gridcolumns: []
        defaultrows: []
        type: singleSelect
        options:
        - ""
        - "No"
        - "Yes"
        fieldassociated: ""
        placeholder: ""
        tooltip: Comments marked “Share Comment with IronDome Community” are shared
          across the IronDome Community. Please do not include enterprise or personal
          information in the comments.
      title: Set IronDefense Alert Status
      description: Set the status of ${incident.name}
      sender: Your SOC team
      expired: false
      totalanswers: 0
  "26":
    id: "26"
    taskid: 134a4a3c-ad82-4115-89d0-bb07c95a5f78
    type: regular
    task:
      id: 134a4a3c-ad82-4115-89d0-bb07c95a5f78
      version: -1
      name: Submit Alert Status to IronDefense
      script: IronDefense|||irondefense-set-alert-status
      type: regular
      iscommand: true
      brand: IronDefense
    nexttasks:
      '#none#':
      - "8"
      - "1"
    scriptarguments:
      alert_id:
        simple: ${incident.labels.id}
      comments:
        simple: ${Set IronDefense Alert Status.Answers.1}
      share_comment_with_irondome:
        simple: ${Set IronDefense Alert Status.Answers.2}
      status:
        simple: ${Set IronDefense Alert Status.Answers.0}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1472.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "16_18_yes": 0.28,
      "17_19_yes": 0.82
    },
    "paper": {
      "dimensions": {
        "height": 2660,
        "width": 1915,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Enrich
  value:
    simple: "True"
  required: false
  description: Should preform enrichment on all indicators in the incident
outputs: []
