id: ExtraHop - CVE-2019-0708 (BlueKeep)
version: -1
name: ExtraHop - CVE-2019-0708 (BlueKeep)
description: |-
  This server received a Remote Desktop Protocol (RDP) connection request that is consistent with a known vulnerability, also known as BlueKeep, in older versions of Microsoft Windows. This vulnerability allows an unauthenticated attacker to remotely run arbitrary code on an RDP server. The attacker can then tamper with data or install malware that could propagate to other Windows devices across the network. Investigate to determine if this server is hosting a version affected by CVE-2019-0708: Windows 7, Windows XP, Windows Vista, Windows Server 2003, and Windows Server 2008.

  MITIGATION OPTIONS
  - Disable Remote Desktop Services if they are not required
  - Implement Network Level Authentication (NLA) on systems running supported versions of Windows 7, Windows Server 2008, and Windows Server 2008 R2
  - Configure firewalls to block traffic on TCP port 3389
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 71394f2c-bc76-4885-8bab-b55ce0094789
    type: start
    task:
      id: 71394f2c-bc76-4885-8bab-b55ce0094789
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": -460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: f4953d89-2219-4d74-8acf-d819728d0ac9
    type: title
    task:
      id: f4953d89-2219-4d74-8acf-d819728d0ac9
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: ecfc91cc-4c7f-49f7-8b44-92db82ef39b9
    type: condition
    task:
      id: ecfc91cc-4c7f-49f7-8b44-92db82ef39b9
      version: -1
      name: Is ExtraHop Reveal(x) enabled?
      description: Checks if there is an active instance of the ExtraHop Reveal(x)
        integration enabled.
      scriptName: Exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "16"
    scriptarguments:
      value:
        complex:
          root: modules
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: brand
                iscontext: true
              right:
                value:
                  simple: ExtraHop
          - - operator: isEqualString
              left:
                value:
                  simple: state
                iscontext: true
              right:
                value:
                  simple: active
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -10,
          "y": -320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: e3c09165-9a69-43e7-85be-7897fb8a7b15
    type: regular
    task:
      id: e3c09165-9a69-43e7-85be-7897fb8a7b15
      version: -1
      name: CVE Search
      description: Search CVE by ID.
      script: CVE Search|||cve-search
      type: regular
      iscommand: true
      brand: CVE Search
    nexttasks:
      '#none#':
      - "17"
      - "19"
    scriptarguments:
      cveId:
        simple: CVE-2019-0708
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": -120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 7a9ab395-3173-4d7a-878a-2329729d255f
    type: playbook
    task:
      id: 7a9ab395-3173-4d7a-878a-2329729d255f
      version: -1
      name: ExtraHop - Get Peers by Host
      description: Given a host, the playbook will retrieve the peer network devices
        that communicated with that host in a given time range.  In addition to a
        list of peers and protocols (sorted by bytes) the playbook returns a link
        to the ExtraHop Live Activity Map to visualize the peer relationships.
      playbookName: ExtraHop - Get Peers by Host
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      from_time:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: subtraction
            args:
              by:
                value:
                  simple: "1800"
      ip:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: victim
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      mac:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: victim
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: macaddress
      name:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: victim
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: dnsname
      until_time:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: addition
            args:
              by:
                value:
                  simple: "1800"
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 210,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: e23d12f7-51d3-4feb-89fa-ebed4a049514
    type: playbook
    task:
      id: e23d12f7-51d3-4feb-89fa-ebed4a049514
      version: -1
      name: Block IP - Generic
      description: |-
        This playbook blocks malicious IPs using all integrations that you have enabled.

        Supported integrations for this playbook:
        * Check Point Firewall
        * Palo Alto Networks Minemeld
        * Palo Alto Networks Panorama
        * Zscaler
      playbookName: Block IP - Generic
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      IP:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: offender
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      IPBlacklistMiner: {}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 810,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: 13d6422c-cd62-4217-852d-0bf472fcd063
    type: condition
    task:
      id: 13d6422c-cd62-4217-852d-0bf472fcd063
      version: -1
      name: Block Offender IP?
      description: Ask ExtraHop analysts whether or not to automatically block the
        offender IP address.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "Yes":
      - "18"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 620,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
        simple: ExtraHop
      subject:
        simple: CVE-2019-0708 RDP Exploit Attempt - Block Offender IP?
      body:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: offender
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      methods:
      - email
      format: ""
      bcc: null
      cc: null
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
      replyOptions:
      - "Yes"
      - "No"
  "20":
    id: "20"
    taskid: 0918f8af-3369-4a6f-8892-c0ec349d8d9e
    type: regular
    task:
      id: 0918f8af-3369-4a6f-8892-c0ec349d8d9e
      version: -1
      name: Investigation and Mitigation Steps
      description: |-
        Investigate to determine if the victim server is hosting a version affected by CVE-2019-0708: Windows 7, Windows XP, Windows Vista, Windows Server 2003, and Windows Server 2008.

        Mitigation Options
        - Disable Remote Desktop Services if they are not required
        - Implement Network Level Authentication (NLA) on systems running supported versions of Windows 7, Windows Server 2008, and Windows Server 2008 R2
        - Configure firewalls to block traffic on TCP port 3389
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 7509459a-ebf7-4788-851c-7a7770982335
    type: regular
    task:
      id: 7509459a-ebf7-4788-851c-7a7770982335
      version: -1
      name: ExtraHop Get Associated Transaction Records
      description: Query records associated with this detection from ExtraHop.
      script: '|||extrahop-query-records'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      field1:
        simple: clientAddr
      field2:
        simple: serverAddr
      limit: {}
      match_type: {}
      offset: {}
      operator1:
        simple: =
      operator2:
        simple: =
      query_from:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
      query_until:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: addition
            args:
              by:
                value:
                  simple: "2"
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
      types:
        simple: rdp_close,rdp_tick
      value1:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: offender
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      value2:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: victim
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "22":
    id: "22"
    taskid: 7a6218f1-8b3f-41e5-8657-cf1dc48150b7
    type: regular
    task:
      id: 7a6218f1-8b3f-41e5-8657-cf1dc48150b7
      version: -1
      name: ExtraHop Get PCAP File
      description: Search for the specific packets associated with this detection
        in ExtraHop and return the pcap file.
      script: '|||extrahop-search-packets'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      bpf: {}
      ip1:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: offender
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      ip2:
        complex:
          root: incident
          accessor: participants
          transformers:
          - operator: WhereFieldEquals
            args:
              equalTo:
                value:
                  simple: victim
              field:
                value:
                  simple: role
              getField:
                value:
                  simple: ipaddress
      limit_bytes: {}
      limit_search_duration: {}
      output: {}
      port1: {}
      port2:
        simple: "3389"
      query_from:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
      query_until:
        complex:
          root: incident
          accessor: occurred
          transformers:
          - operator: toUnix
          - operator: addition
            args:
              by:
                value:
                  simple: "2"
          - operator: multiply
            args:
              by:
                value:
                  simple: "1000"
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 410
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {
      "15_2_#default#": 0.12,
      "19_18_Yes": 0.55,
      "19_2_#default#": 0.14
    },
    "paper": {
      "dimensions": {
        "height": 1315,
        "width": 1200,
        "x": -10,
        "y": -460
      }
    }
  }
inputs: []
outputs: []
