id: playbook-FeedAutofocus_test.yml
version: -1
contentitemexportablefields:
  contentitemfields:
    propagationLabels: []
name: playbook-FeedAutofocus_test.yml
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: "1"
    type: start
    task:
      id: "1"
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: "2"
    type: regular
    task:
      id: "2"
      version: -1
      name: DeleteContext
      script: DeleteContext
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: "6"
    type: regular
    task:
      id: "6"
      version: -1
      name: autofocus-get-indicators
      script: '|||autofocus-get-indicators'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      limit:
        simple: "100"
      offset:
        simple: "0"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: "4"
    type: condition
    task:
      id: "4"
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: AutoFocusFeed.Indicator.Type
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              simple: AutoFocusFeed.Indicator.Value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 600
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: "5"
    type: title
    task:
      id: "5"
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 800
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 815,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
